### ISSUE TITLE
Syncs failing with PSQLException: ERROR: cannot cast type record to simple_name

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1007]
I was going to run sync for 60 WoRMS checklists on prod clb but the first couple failed.

[Logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/-89-Q3kBU86CouzbqX2N?_a=(columns:!(level,sectorKey,service,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:sector,negate:!f,params:(query:'1267'),type:phrase),query:(match_phrase:(sector:'1267'))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:attempt,negate:!f,params:(query:'3'),type:phrase),query:(match_phrase:(attempt:'3')))))&_g=(filters:!())):
```
org.postgresql.util.PSQLException: ERROR: cannot cast type record to simple_name
  Detail: Input has too few columns.
  Where: PL/pgSQL function classification_sn(integer,text,boolean) line 17 at EXECUTE
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.queryCursor(PreparedStatementHandler.java:71)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.queryCursor(RoutingStatementHandler.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQueryCursor(SimpleExecutor.java:75)
	at org.apache.ibatis.executor.BaseExecutor.queryCursor(BaseExecutor.java:178)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:123)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:116)
	at org.apache.ibatis.binding.MapperMethod.executeForCursor(MapperMethod.java:167)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:84)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy140.processTree(Unknown Source)
	at life.catalogue.dao.NameUsageProcessor.processTree(NameUsageProcessor.java:73)
	at life.catalogue.dao.NameUsageProcessor.processSector(NameUsageProcessor.java:66)
	at life.catalogue.es.nu.NameUsageIndexServiceEs.indexSector(NameUsageIndexServiceEs.java:147)
	at life.catalogue.assembly.SectorSync.updateSearchIndex(SectorSync.java:87)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:111)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: cannot cast type record to simple_name
  Detail: Input has too few columns.
  Where: PL/pgSQL function classification_sn(integer,text,boolean) line 17 at EXECUTE
### The error may involve life.catalogue.db.mapper.NameUsageWrapperMapper.processTree-Inline
### The error occurred while setting parameters
### SQL: WITH RECURSIVE tree AS (       SELECT ? AS uid, classification_sn(?, ?, true) AS classification     UNION ALL       SELECT u.id, array_append(tree.classification, (u.id,n.rank,n.scientific_name,n.authorship)::simple_name)       FROM name_usage_3 u JOIN name_3 n ON u.name_id=n.id JOIN tree ON (tree.uid = u.parent_id)             WHERE u.sector_key = ?           )     SELECT * FROM tree             WHERE uid != ? OR (SELECT sector_key=? FROM name_usage_3 WHERE id=?)
### Cause: org.postgresql.util.PSQLException: ERROR: cannot cast type record to simple_name
  Detail: Input has too few columns.
  Where: PL/pgSQL function classification_sn(integer,text,boolean) line 17 at EXECUTE
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:127)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:116)
	at org.apache.ibatis.binding.MapperMethod.executeForCursor(MapperMethod.java:167)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:84)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy140.processTree(Unknown Source)
	at life.catalogue.dao.NameUsageProcessor.processTree(NameUsageProcessor.java:73)
	at life.catalogue.dao.NameUsageProcessor.processSector(NameUsageProcessor.java:66)
	at life.catalogue.es.nu.NameUsageIndexServiceEs.indexSector(NameUsageIndexServiceEs.java:147)
	at life.catalogue.assembly.SectorSync.updateSearchIndex(SectorSync.java:87)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:111)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:32)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: cannot cast type record to simple_name
  Detail: Input has too few columns.
  Where: PL/pgSQL function classification_sn(integer,text,boolean) line 17 at EXECUTE
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.queryCursor(PreparedStatementHandler.java:71)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.queryCursor(RoutingStatementHandler.java:84)
	at org.apache.ibatis.executor.SimpleExecutor.doQueryCursor(SimpleExecutor.java:75)
	at org.apache.ibatis.executor.BaseExecutor.queryCursor(BaseExecutor.java:178)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectCursor(DefaultSqlSession.java:123)
	... 16 common frames omitted
```

**Comment by mdoering** [comment]
please try again, I missed a function update in the db
