### ISSUE TITLE
Myriatrix import NPE

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1018]
importing https://www.checklistbank.org/dataset/6282/imports DWCA generates a NPE:
Error processing batch 1 for life.catalogue.importer.Normalizer$1@5e28ad96, skip remaining 3 batches

It works in GBIF and locally too

**Comment by mdoering** [comment]
latest:

```
java.lang.NullPointerException: null
	at life.catalogue.importer.Normalizer$1.process(Normalizer.java:228)
	at life.catalogue.importer.neo.NodeBatchProcessor$BatchConsumer.run(NodeBatchProcessor.java:64)
```

and

```
org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.impl.util.watcher.DefaultFileSystemWatcherService@771767f6' failed to stop. Please see the attached cause exception "null".
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:488)
	at org.neo4j.kernel.lifecycle.LifeSupport.stopInstances(LifeSupport.java:161)
	at org.neo4j.kernel.lifecycle.LifeSupport.stop(LifeSupport.java:143)
	at org.neo4j.kernel.lifecycle.LifeSupport.shutdown(LifeSupport.java:191)
	at org.neo4j.kernel.impl.factory.ClassicCoreSPI.shutdown(ClassicCoreSPI.java:180)
	at org.neo4j.kernel.impl.factory.GraphDatabaseFacade.shutdown(GraphDatabaseFacade.java:364)
	at life.catalogue.importer.neo.NeoDb.closeNeo(NeoDb.java:182)
	at life.catalogue.importer.neo.NeoDb.close(NeoDb.java:143)
	at life.catalogue.importer.Normalizer.call(Normalizer.java:113)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:246)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:134)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException: null
	at java.base/java.lang.Object.wait(Native Method)
	at java.base/java.lang.Thread.join(Thread.java:1305)
	at java.base/java.lang.Thread.join(Thread.java:1380)
	at org.neo4j.kernel.impl.util.watcher.DefaultFileSystemWatcherService.stop(DefaultFileSystemWatcherService.java:68)
	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.stop(LifeSupport.java:480)
	... 15 common frames omitted

```

**Comment by mdoering** [comment]
Import is working on dev now.
