### ISSUE TITLE
Search exceptions for large offsets

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1063]
http://api.catalogueoflife.org/dataset/2349/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=extinct&facet=environment&limit=50&offset=4418350&reverse=false&sortBy=taxonomic&status=_NOT_NULL

```
{"type": "server", "timestamp": "2021-11-15T10:32:19,328Z", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "col", "node.name": "node-col", "message": "[xTwUbd7mSvuFGdFtYPbj8A][col-2021-03-26][0]: Failed to execute [SearchRequest{searchType=QUERY_THEN_FETCH, indices=[prod-nu], indicesOptions=IndicesOptions[ignore_unavailable=false, allow_no_indices=true, expand_wildcards_open=true, expand_wildcards_closed=false, expand_wildcards_hidden=false, allow_aliases_to_multiple_indices=true, forbid_closed_indices=true, ignore_aliases=false, ignore_throttled=true], types=[], routing='null', preference='null', requestCache=null, scroll=null, maxConcurrentShardRequests=0, batchedReduceSize=512, preFilterShardSize=null, allowPartialSearchResults=true, localClusterAlias=null, getOrCreateAbsoluteStartMillis=-1, ccsMinimizeRoundtrips=true, source={\"from\":4418350,\"size\":50,\"query\":{\"bool\":{\"filter\":[{\"term\":{\"datasetKey\":{\"value\":2349,\"boost\":1.0}}},{\"exists\":{\"field\":\"status\",\"boost\":1.0}}],\"adjust_pure_negative\":true,\"boost\":1.0}},\"sort\":[{\"rank\":{\"order\":\"asc\"}},{\"scientificName\":{\"order\":\"asc\"}}],\"track_total_hits\":2147483647,\"aggregations\":{\"_global_\":{\"global\":{},\"aggregations\":{\"_filter_\":{\"filter\":{\"term\":{\"datasetKey\":{\"value\":2349,\"boost\":1.0}}},\"aggregations\":{\"FIELD\":{\"filter\":{\"exists\":{\"field\":\"status\",\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"nameFields\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}},\"ISSUE\":{\"filter\":{\"exists\":{\"field\":\"status\",\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"issues\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}},\"NOM_STATUS\":{\"filter\":{\"exists\":{\"field\":\"status\",\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"nomStatus\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}},\"RANK\":{\"filter\":{\"exists\":{\"field\":\"status\",\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"rank\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}},\"STATUS\":{\"filter\":{\"match_all\":{\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"status\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}},\"NAME_TYPE\":{\"filter\":{\"exists\":{\"field\":\"status\",\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"type\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}},\"EXTINCT\":{\"filter\":{\"exists\":{\"field\":\"status\",\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"extinct\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}},\"ENVIRONMENT\":{\"filter\":{\"exists\":{\"field\":\"status\",\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"environments\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}},\"AUTHORSHIP\":{\"filter\":{\"exists\":{\"field\":\"status\",\"boost\":1.0}},\"aggregations\":{\"_values_\":{\"terms\":{\"field\":\"authorship\",\"size\":50,\"min_doc_count\":1,\"shard_min_doc_count\":0,\"show_term_doc_count_error\":false,\"order\":[{\"_count\":\"desc\"},{\"_key\":\"asc\"}]}}}}}}}}}}}] lastShard [true]", "cluster.uuid": "VSaAkBhoQg67yXoFlbafkg", "node.id": "xTwUbd7mSvuFGdFtYPbj8A" , 
"stacktrace": ["org.elasticsearch.transport.RemoteTransportException: [node-col][130.225.43.29:9300][indices:data/read/search[phase/query]]",
"Caused by: java.lang.IllegalArgumentException: Result window is too large, from + size must be less than or equal to: [2000000] but was [4418400]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.",
"at org.elasticsearch.search.DefaultSearchContext.preProcess(DefaultSearchContext.java:192) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:113) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.SearchService.createContext(SearchService.java:732) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:422) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.SearchService.access$500(SearchService.java:135) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.2.jar:7.11.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]"] }
{"type": "server", "timestamp": "2021-11-15T10:32:19,339Z", "level": "DEBUG", "component": "o.e.a.s.TransportSearchAction", "cluster.name": "col", "node.name": "node-col", "message": "All shards failed for phase: [query]", "cluster.uuid": "VSaAkBhoQg67yXoFlbafkg", "node.id": "xTwUbd7mSvuFGdFtYPbj8A" , 
"stacktrace": ["org.elasticsearch.ElasticsearchException$1: Result window is too large, from + size must be less than or equal to: [2000000] but was [4418400]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.",
"at org.elasticsearch.ElasticsearchException.guessRootCauses(ElasticsearchException.java:633) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.executeNextPhase(AbstractSearchAsyncAction.java:330) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onPhaseDone(AbstractSearchAsyncAction.java:636) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.onShardFailure(AbstractSearchAsyncAction.java:415) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction.access$000(AbstractSearchAsyncAction.java:59) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.search.AbstractSearchAsyncAction$1.onFailure(AbstractSearchAsyncAction.java:264) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.search.SearchExecutionStatsCollector.onFailure(SearchExecutionStatsCollector.java:62) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.ActionListenerResponseHandler.handleException(ActionListenerResponseHandler.java:48) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.search.SearchTransportService$ConnectionCountingHandler.handleException(SearchTransportService.java:404) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.transport.TransportService$6.handleException(TransportService.java:743) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.transport.TransportService$ContextRestoreResponseHandler.handleException(TransportService.java:1288) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.transport.TransportService$DirectResponseChannel.processException(TransportService.java:1397) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.transport.TransportService$DirectResponseChannel.sendResponse(TransportService.java:1371) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.transport.TaskTransportChannel.sendResponse(TaskTransportChannel.java:50) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.transport.TransportChannel.sendErrorResponse(TransportChannel.java:45) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.support.ChannelActionListener.onFailure(ChannelActionListener.java:40) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.ActionRunnable.onFailure(ActionRunnable.java:77) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:28) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.TimedRunnable.doRun(TimedRunnable.java:33) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingAbstractRunnable.doRun(ThreadContext.java:732) [elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) [elasticsearch-7.11.2.jar:7.11.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]",
"at java.lang.Thread.run(Thread.java:832) [?:?]",
"Caused by: java.lang.IllegalArgumentException: Result window is too large, from + size must be less than or equal to: [2000000] but was [4418400]. See the scroll api for a more efficient way to request large data sets. This limit can be set by changing the [index.max_result_window] index level setting.",
"at org.elasticsearch.search.DefaultSearchContext.preProcess(DefaultSearchContext.java:192) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.query.QueryPhase.preProcess(QueryPhase.java:113) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.SearchService.createContext(SearchService.java:732) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:422) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.SearchService.access$500(SearchService.java:135) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.search.SearchService$2.lambda$onResponse$0(SearchService.java:395) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.ActionRunnable.lambda$supply$0(ActionRunnable.java:47) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.action.ActionRunnable$2.doRun(ActionRunnable.java:62) ~[elasticsearch-7.11.2.jar:7.11.2]",
"at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:26) ~[elasticsearch-7.11.2.jar:7.11.2]",
"... 6 more"] }

```

**Comment by mdoering** [comment]
@thomasstjerne can you think of any place the UI would create a call with such a large `offset=4418350`?

**Comment by mdoering** [comment]
Resitrict paging to an offset of 100.000 to block deep paging.

**Comment by ayco-at-naturalis** [comment]
BTW My eye just happened to fall on this issue ... if it's crucial, you can increase the max_result_window of the index to, say, 1000000. Not advised by ES, I haven't encountered problems with it

**Comment by mdoering** [comment]
Thanks @ayco-at-naturalis, I think it's fine to have a maximum offset. You can use downloads to retrieve entire datasets or larger subsets.

While I have your attention, could you maybe take a look at this issue and suggest a solution?
https://github.com/CatalogueOfLife/backend/issues/992
