### ISSUE TITLE
Exporter failing with FileNotFoundException for VernacularName.tsv

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1065]
@mdoering, I saw your message yesterday about the exporter being fixed on the CoL users list, but it's still failing for me on prod with the deployed code.

[Logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/Ni5hJX0BBVmQ6cT2QCQx?_g=(filters:!())&_a=(columns:!(level,logger_name,message),filters:!()))
```
java.nio.file.NoSuchFileException: /mnt/auto/col/exports/a5/a5af32ba-8f59-4ec6-af85-fe6e74258592.zip
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.Files.size(Files.java:2380)
	at life.catalogue.exporter.DatasetExporter.onFinish(DatasetExporter.java:165)
	at life.catalogue.concurrent.BackgroundJob.run(BackgroundJob.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
java.lang.RuntimeException: java.io.FileNotFoundException: /tmp/col/scratch/export/a5af32ba-8f59-4ec6-af85-fe6e74258592/VernacularName.tsv (No such file or directory)
	at life.catalogue.common.io.TabWriter.fromFile(TabWriter.java:32)
	at life.catalogue.common.io.TermWriter$TSV.setupWriter(TermWriter.java:47)
	at life.catalogue.common.io.TermWriter$TSV.<init>(TermWriter.java:42)
	at life.catalogue.exporter.ArchiveExporter.newDataFile(ArchiveExporter.java:435)
	at life.catalogue.exporter.ArchiveExporter.exportTaxonExtension(ArchiveExporter.java:288)
	at life.catalogue.exporter.ArchiveExporter.exportTaxonRels(ArchiveExporter.java:250)
	at life.catalogue.exporter.ArchiveExporter.export(ArchiveExporter.java:103)
	at life.catalogue.exporter.DatasetExporter.runWithLock(DatasetExporter.java:136)
	at life.catalogue.concurrent.DatasetBlockingJob.execute(DatasetBlockingJob.java:54)
	at life.catalogue.concurrent.BackgroundJob.run(BackgroundJob.java:69)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.io.FileNotFoundException: /tmp/col/scratch/export/a5af32ba-8f59-4ec6-af85-fe6e74258592/VernacularName.tsv (No such file or directory)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:298)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:237)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:187)
	at life.catalogue.common.io.TabWriter.fromFile(TabWriter.java:30)
	... 14 common frames omitted
```

**Comment by mdoering** [comment]
saw that and looking into it. Comes as a surprise and is unrelated to the fix I deployed earlier.

**Comment by mdoering** [comment]
running the exact same export works just fine. I'll close the issue, please reopen if it happens again!

**Comment by mdoering** [comment]
here is the export: https://download.catalogueoflife.org/exports/ee/ee05f3b7-ec2c-4c12-a0ca-156591d891bd.zip
