### ISSUE TITLE
Status 500 on user role update (PUT)

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1119]
I tried with both upper- and lowercased roles:

Request failed with status code 500
There was an error processing your request. It has been logged (ID 4ac156c8436082f9).

HTTP method: PUT

https://api.dev.checklistbank.org/user/117/role

Body:
["editor"]

**Comment by mdoering** [comment]
indeed a SQL bug:

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.apache.ibatis.binding.BindingException: Parameter 'reviewer' not found. Available parameters are [editor, param1, userKey, param2]
### The error may exist in life/catalogue/db/mapper/DatasetMapper.xml
### The error may involve life.catalogue.db.mapper.DatasetMapper.removeReviewerEverywhere-Inline
### The error occurred while setting parameters
### SQL: UPDATE dataset  SET (acl_reviewer, modified_by, modified) =     ( array_remove(acl_reviewer, ?), ?, now() )     WHERE acl_reviewer @> ARRAY[?::int]
### Cause: org.apache.ibatis.binding.BindingException: Parameter 'reviewer' not found. Available parameters are [editor, param1, userKey, param2]
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy57.removeReviewerEverywhere(Unknown Source)
	at life.catalogue.dao.UserDao.changeRole(UserDao.java:73)

```

**Comment by mdoering** [comment]
should be good on dev now

**Comment by thomasstjerne** [comment]
> should be good on dev now

It is. Thanks
