### ISSUE TITLE
Duplicate download error

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1123]
from /dataset/2007/duplicate.csv?catalogueKey=3&limit=50&minSize=2&rank=genus&rankDifferent=false

```
at com.sun.proxy.$Proxy138.usagesByIds(Unknown Source)
	at life.catalogue.dao.DuplicateDao.findOrList(DuplicateDao.java:209)
	at life.catalogue.dao.DuplicateDao.list(DuplicateDao.java:147)

Caused by: java.io.IOException: Tried to send an out-of-range integer as a 2-byte value: 70116
	at org.postgresql.core.PGStream.sendInteger2(PGStream.java:356)
	at org.postgresql.core.v3.QueryExecutorImpl.sendParse(QueryExecutorImpl.java:1603)
	at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1486)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:346)
```

**Comment by mdoering** [comment]
> The exception occurs because of PostgreSQL's limit of 32767 bind variables per statement. As a possible workaround try to split your large query into smaller ones.

https://stackoverflow.com/questions/49274390/postgresql-and-hibernate-java-io-ioexception-tried-to-send-an-out-of-range-inte
