### ISSUE TITLE
IllegalStateException: Failed to init NormalizerStore at /tmp/col/scratch/131219/normalizer

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#1147]
This occurred after an import was aborted using the stop button. Subsequently it has not been possible to trigger a new import
https://www.dev.checklistbank.org/dataset/131219/imports

**Comment by mdoering** [comment]
@gdower reported the same some time ago. Will look...

**Comment by mdoering** [comment]
Damn, now it is working. I had deployed a new version to dev in the meantime. I suppose starting a new JVM has fixed it.
I would not be surprised if it is related to our other mysterious problem that shows sometimes - files being kept open:
https://github.com/CatalogueOfLife/backend/issues/1132

**Comment by mdoering** [comment]
I've canceled and reimported - now it fails again!

**Comment by mdoering** [comment]
> Caused by: org.neo4j.kernel.lifecycle.LifecycleException: Component 'org.neo4j.kernel.internal.locker.StoreLockerLifecycleAdapter@1a755a96' was successfully initialized, but failed to start. Please see the attached cause exception "Unable to obtain lock on store lock file: /tmp/col/scratch/131219/normalizer/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)".
> 	at org.neo4j.kernel.lifecycle.LifeSupport$LifecycleInstance.start(LifeSupport.java:466)
> 	at org.neo4j.kernel.lifecycle.LifeSupport.start(LifeSupport.java:107)
> 	at org.neo4j.kernel.impl.factory.GraphDatabaseFacadeFactory.initFacade(GraphDatabaseFacadeFactory.java:208)
> 	... 17 common frames omitted
> Caused by: org.neo4j.kernel.StoreLockException: Unable to obtain lock on store lock file: /tmp/col/scratch/131219/normalizer/store_lock. Please ensure no other process is using this database, and that the directory is writable (required even for read-only access)

**Comment by mdoering** [comment]
Yes. The jobs are in fact not cancelled at all, the name parser catches the exception but does not do anything with it. It is definitely the same as #1143 1132
