### ISSUE TITLE
Network errors

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1155]
In both clb and the portal we get network errors pretty frequently. The Google bot also hits these errors which probably could hurt page rank:

https://www.google.com/search?q=site%3Acatalogueoflife.org+network+error

I suspect it might be the caching server and do not think it is any particular endpoint, but I'll try to capture more information the next time I hit it.

**Comment by mdoering** [comment]
I would really like to better understand what goes wrong in these cases. It's not immediately clear. @thomasstjerne any ideas?

**Comment by thomasstjerne** [comment]
@gdower do you ever see the Network Errors on the initial page load? I only see them when I return to a browser tab opened hours earlier / day before and suspect that these are mostly network changes.

**Comment by mdoering** [comment]
Since the varnish cache was started 8.5 days ago the backend produced 124 errors out of 6.5 million requests served. I doubt this is the problem. There is a timeout of 5 minutes if the backend does not starts responding until then. That also does not seem to be hit much. Still a bit mysterious to me whats causing this.

As the vast majority of API calls just poll the maintenance status and even those return some 503s I have changed the API to write the maintenance status into a static file served by apache. That avoids varnish and the backend to serve the same over and over (we cannot cache it either as it needs to be potentially updated quickly). Maybe that brings some light into the tunnel.

**Comment by mdoering** [comment]
Personally I have not seen a single network error all of today. Neither in my browser nor in the logs since 2 hours

**Comment by gdower** [comment]
I finally caught a network error in the console while trying to upload a zip archive for import. It says CORS failed for the OPTIONS request and NS_ERROR_DOM_BAD_URI for the POST. The domain is correct so maybe it is caused by Varnish responding with an error? I can't view the response body because of CORS.

![image](https://user-images.githubusercontent.com/8573609/214363174-161ca31d-7e4f-4007-b91c-e8157c83ecae.png)

![image](https://user-images.githubusercontent.com/8573609/214362338-9a581f9e-fd97-406a-a2fa-b67346b50a21.png)

**Comment by mdoering** [comment]
Hm, if the option request fails then the subsequent one fails too. I am surprised the browser actually still tries to call without a successful OPTION response. 

Just why the OPTION one failed is unclear to me. @thomasstjerne any insight maybe?

**Comment by thomasstjerne** [comment]
Afraid I don´t really have any good ideas on this

**Comment by gdower** [comment]
I caught another one and this one had the varnish cache server error.

![image](https://user-images.githubusercontent.com/8573609/217019719-6c836bb8-050e-4342-9f14-0ce8509a1de4.png)

1) That first failed response had the body:

{
"message":"Service Unavailable",
"url":"/importer",
"status":"503"
}

2) The 2nd one had the body:

<hr>
<!DOCTYPE html>
<html>
  <head>
    <title>503 Backend fetch failed</title>
  </head>
  <body>
    <h1>Error 503 Backend fetch failed</h1>
    <p>Backend fetch failed</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 93815103</p>
    <p>Varnish cache server</p>
  </body>
</html>
<hr>

3) The rest of them have `Response body is not available to scripts (Reason: CORS Preflight Did Not Succeed)` errors with no response body.

Here's the [logs for that time period](https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-02-06T15:46:00.000Z',to:'2023-02-06T15:49:00.000Z'))&_a=(columns:!(level,logger_name,message),filters:!(),index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',interval:auto,query:(language:kuery,query:''),sort:!())) and there are a couple of errors in there, but maybe this is the one at 2023-02-06 15:48:13.142 which corresponds closely with my browser request time of Mon, 06 Feb 2023 15:48:17 GMT?

```
org.neo4j.kernel.impl.store.UnderlyingStorageException: java.nio.channels.ClosedByInterruptException
	at org.neo4j.kernel.impl.store.MetaDataStore.scanAllFields(MetaDataStore.java:623)
	at org.neo4j.kernel.impl.store.MetaDataStore.refreshFields(MetaDataStore.java:605)
	at org.neo4j.kernel.impl.store.MetaDataStore.checkInitialized(MetaDataStore.java:825)
	at org.neo4j.kernel.impl.store.MetaDataStore.getLastCommittedTransactionId(MetaDataStore.java:772)
	at org.neo4j.kernel.impl.store.CountsComputer.recomputeCounts(CountsComputer.java:45)
	at org.neo4j.unsafe.batchinsert.internal.BatchInserterImpl.rebuildCounts(BatchInserterImpl.java:568)
	at org.neo4j.unsafe.batchinsert.internal.BatchInserterImpl.shutdown(BatchInserterImpl.java:1001)
	at org.neo4j.unsafe.batchinsert.internal.FileSystemClosingBatchInserter.shutdown(FileSystemClosingBatchInserter.java:184)
	at life.catalogue.importer.neo.NeoDb.endBatchMode(NeoDb.java:432)
	at life.catalogue.importer.NeoCsvInserter.insertAll(NeoCsvInserter.java:131)
	at life.catalogue.importer.Normalizer.insertData(Normalizer.java:915)
	at life.catalogue.importer.Normalizer.call(Normalizer.java:100)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:303)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.channels.ClosedByInterruptException: null
	at java.base/java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:199)
	at java.base/sun.nio.ch.FileChannelImpl.endBlocking(FileChannelImpl.java:162)
	at java.base/sun.nio.ch.FileChannelImpl.readInternal(FileChannelImpl.java:816)
	at java.base/sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:796)
	at org.neo4j.io.fs.StoreFileChannel.read(StoreFileChannel.java:99)
	at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.swapIn(SingleFilePageSwapper.java:240)
	at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.readAndRetryIfInterrupted(SingleFilePageSwapper.java:300)
	at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.read(SingleFilePageSwapper.java:290)
	at org.neo4j.io.pagecache.impl.muninn.PageList.fault(PageList.java:434)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.pageFault(MuninnPageCursor.java:391)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.uncommonPin(MuninnPageCursor.java:340)
	at org.neo4j.io.pagecache.impl.muninn.MuninnPageCursor.pin(MuninnPageCursor.java:308)
	at org.neo4j.io.pagecache.impl.muninn.MuninnReadPageCursor.next(MuninnReadPageCursor.java:60)
	at org.neo4j.kernel.impl.store.MetaDataStore.scanAllFields(MetaDataStore.java:616)
	... 18 common frames omitted
	Suppressed: java.io.FileNotFoundException: /tmp/col/scratch/1027/normalizer/neostore (No such file or directory)
		at java.base/java.io.RandomAccessFile.$$YJP$$open0(Native Method)
		at java.base/java.io.RandomAccessFile.open0(RandomAccessFile.java)
		at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:345)
		at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:259)
		at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
		at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:69)
		at org.neo4j.io.fs.DefaultFileSystemAbstraction.open(DefaultFileSystemAbstraction.java:54)
		at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.tryReopen(SingleFilePageSwapper.java:657)
		at org.neo4j.io.pagecache.impl.SingleFilePageSwapper.readAndRetryIfInterrupted(SingleFilePageSwapper.java:309)
		... 25 common frames omitted
```

**Comment by mdoering** [comment]
These were just during a restart of the server which puts the API down for half a minute.
During a regular deploy we spin up a new server while we keep the old running and then just switch varnish to the new one. That works without any downtime. But a restart of the existing deploy needs to shut down and start up again which takes some time. Especially starting up the names index, which is needed for matching, imports & syncs, can take some minutes. So these causes are not bugs, they are just maintainance related outages.

@timrobertson100 @MattBlissett in case we need to fix a broken server again consider if a col-prod-deploy is feasable. At least when the existing service is not yet fully down a new deploy keeps downtimes minimal. If the server is unresponsive anyways it doesnt matter and a simple restart is probably better.
