### ISSUE TITLE
Fix errors in single char config

### ISSUE THREAD

**Issue by timrobertson100** [CatalogueOfLife/backend#1173]
The [commit](https://github.com/CatalogueOfLife/backend/commit/8ba619903cec97522fa58ebe53b79f1bc3ae8b78) to enforce single char for CSV delimiters has broken production.

```
ERROR [2022-11-02 08:17:17,437] life.catalogue.importer.ImportJob: Dataset 1199 import failed. class java.lang.Character cannot be cast to class java.lang.String (java.lang.Character and java.lang.String are in module java.base of loader 'bootstrap')
! java.lang.ClassCastException: class java.lang.Character cannot be cast to class java.lang.String (java.lang.Character and java.lang.String are in module java.base of loader 'bootstrap')
! at life.catalogue.api.model.DatasetSettings.getString(DatasetSettings.java:43)
! at life.catalogue.importer.NeoCsvInserter.<init>(NeoCsvInserter.java:72)
! at life.catalogue.importer.coldp.ColdpInserter.<init>(ColdpInserter.java:59)
! at life.catalogue.importer.Normalizer.insertData(Normalizer.java:909)
! at life.catalogue.importer.Normalizer.call(Normalizer.java:100)
! at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:303)
! at life.catalogue.importer.ImportJob.run(ImportJob.java:155)
! at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
! at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
! at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
! at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
! at java.base/java.lang.Thread.run(Thread.java:834)
```

The code appears to verify that it is a single char, and then incorrectly cast it to a string instead of converting it.

**Comment by mdoering** [comment]
fixed with https://github.com/CatalogueOfLife/backend/commit/54a5008770e4d3744ef6319600ffc081e5ff1450
