### ISSUE TITLE
NullPointerException after analyzing stage of import for ACEF

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1192]
I am [trying to re-import FLOW](https://github.com/CatalogueOfLife/data/issues/503#issuecomment-1402162466) using [this archive](https://github.com/CatalogueOfLife/backend/files/10492629/1011.zip) but it fails with a NullPointerException on prod during or after the analyzing stage.

[Logs](https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(columns:!(level,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:dataset,negate:!f,params:(query:'1011'),type:phrase),query:(match_phrase:(dataset:'1011')))),index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',interval:auto,query:(language:lucene,query:''),sort:!())):
```
java.lang.NullPointerException: null
	at life.catalogue.es.nu.NameUsageIndexServiceEs.lambda$indexNameUsages$4(NameUsageIndexServiceEs.java:301)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at life.catalogue.es.nu.NameUsageIndexServiceEs.indexNameUsages(NameUsageIndexServiceEs.java:305)
	at life.catalogue.es.nu.NameUsageIndexServiceEs.update(NameUsageIndexServiceEs.java:200)
	at life.catalogue.dao.DecisionDao.updateAfter(DecisionDao.java:78)
	at life.catalogue.dao.DecisionDao.updateAfter(DecisionDao.java:23)
	at life.catalogue.dao.EntityDao.update(EntityDao.java:160)
	at life.catalogue.dao.EntityDao.update(EntityDao.java:142)
	at life.catalogue.matching.decision.DecisionRematcher.match(DecisionRematcher.java:48)
	at life.catalogue.matching.decision.DecisionRematcher.match(DecisionRematcher.java:12)
	at life.catalogue.matching.decision.RematcherBase.match(RematcherBase.java:113)
	at life.catalogue.matching.decision.DecisionRematcher.match(DecisionRematcher.java:19)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:321)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:155)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

It [imported successfully on dev with the same settings](https://www.dev.checklistbank.org/dataset/65505/imports). I think maybe it's decision matching that might be causing the importer to crash but I'm leaving it in a broken state so that you can look at it before we turn off decision matching and/or delete the decisions.

**Comment by mdoering** [comment]
Ah, that looks like a true bug related to rematching decisions after importing a project source. I'll work on that today

**Comment by mdoering** [comment]
fixed, deployed and imported fine: https://www.checklistbank.org/dataset/1011/imports
