### ISSUE TITLE
SourceInvalidException: Failed to parse DwC-A descriptor

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1220]
Some Darwin Core Archives failed to import with a "SourceInvalidException: Failed to parse DwC-A descriptor."

[Logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/svz8yIcBOejCygyAqasp?_g=(filters:!())&_a=(columns:!(level,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:dataset,negate:!f,params:(query:'257216'),type:phrase),query:(match_phrase:(dataset:'257216')))))):

```
com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character 't' (code 116) expected '='
 at [row,col {unknown-source}]: [67,33]
	at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:647)
	at com.ctc.wstx.sr.BasicStreamReader.handleNonNsAttrs(BasicStreamReader.java:3125)
	at com.ctc.wstx.sr.BasicStreamReader.handleStartElem(BasicStreamReader.java:2968)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2839)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
	at life.catalogue.csv.DwcaReader.buildSchema(DwcaReader.java:266)
	at life.catalogue.csv.DwcaReader.readFromMeta(DwcaReader.java:381)
	at life.catalogue.csv.DwcaReader.discoverSchemas(DwcaReader.java:131)
	at life.catalogue.csv.CsvReader.<init>(CsvReader.java:110)
	at life.catalogue.csv.DwcaReader.<init>(DwcaReader.java:86)
	at life.catalogue.csv.DwcaReader.from(DwcaReader.java:100)
	at life.catalogue.importer.dwca.DwcaInserter.<init>(DwcaInserter.java:39)
	at life.catalogue.importer.Normalizer.insertData(Normalizer.java:903)
	at life.catalogue.importer.Normalizer.call(Normalizer.java:102)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:308)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mdoering** [comment]
Dataset [257216](https://tb.plazi.org/GgServer/dwca/CB7EFFE7FFD3FFB3E551FFBDFF9C916F.zip) from plazi

**Comment by mdoering** [comment]
@gsautter the above archive contains a bad meta.xml file with this broken line:
>     <field index="25" separator term="http://rs.tdwg.org/dwc/terms/associatedSequences"/>  

The separator token needs to be removed or given a value
