### ISSUE TITLE
ERROR: invalid byte sequence for encoding "UTF8": 0x00

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#1259]
The 0x00 bug that we previously discussed is reproducible:

[Logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/qlEwiooBOejCygyAJKRL?_g=(filters:!())&_a=(columns:!(level,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:dataset,negate:!f,params:(query:'2217'),type:phrase),query:(match_phrase:(dataset:'2217')))))):
```
org.apache.ibatis.exceptions.PersistenceException: 
### Error committing transaction.  Cause: org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.TypeMaterialMapper.create (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 9,377 INSERT INTO type_material ( 
    dataset_key,
    sector_key,
    name_id,
     
    id,
    verbatim_key,
    citation,
    status,
    locality,
    country,
    latitude,
    longitude,
    altitude,
    coordinate,
    sex,
    institution_code,
    catalog_number,
    associated_sequences,
    host,
    date,
    collector,
    reference_id,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    2217,
    NULL,
    '367353',
    'tm5YZ',
    123958,
    'male, ?Ecuador: Orellana, Tiputini Biodiversity Station nr Yasuni National Park Erwin Transect - T/2220-?m?, ?9-ii-1999male, ?Ecuador: Orellana, Tiputini Biodiversity Station nr Yasuni National Park Erwin Transect - T/2220-?m?, ?9-ii-1999?37'55"S 076?08'39"W T.L. Erwin et al Fogging terra firme forest?, EPCN.',
    'HOLOTYPE'::TYPESTATUS,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL::SEX,
    'USNM',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    10,
    10
   , now(), now()) was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00
  Where: unnamed portal parameter $6  Call getNextException to see other errors in the batch.
### Cause: org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.TypeMaterialMapper.create (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 9,377 INSERT INTO type_material ( 
    dataset_key,
    sector_key,
    name_id,
     
    id,
    verbatim_key,
    citation,
    status,
    locality,
    country,
    latitude,
    longitude,
    altitude,
    coordinate,
    sex,
    institution_code,
    catalog_number,
    associated_sequences,
    host,
    date,
    collector,
    reference_id,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    2217,
    NULL,
    '367353',
    'tm5YZ',
    123958,
    'male, ?Ecuador: Orellana, Tiputini Biodiversity Station nr Yasuni National Park Erwin Transect - T/2220-?m?, ?9-ii-1999male, ?Ecuador: Orellana, Tiputini Biodiversity Station nr Yasuni National Park Erwin Transect - T/2220-?m?, ?9-ii-1999?37'55"S 076?08'39"W T.L. Erwin et al Fogging terra firme forest?, EPCN.',
    'HOLOTYPE'::TYPESTATUS,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL::SEX,
    'USNM',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    10,
    10
   , now(), now()) was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00
  Where: unnamed portal parameter $6  Call getNextException to see other errors in the batch.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:226)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:217)
	at life.catalogue.importer.PgImport.insertTypeMaterial(PgImport.java:350)
	at life.catalogue.importer.PgImport.call(PgImport.java:124)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:321)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:158)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.TypeMaterialMapper.create (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 9,377 INSERT INTO type_material ( 
    dataset_key,
    sector_key,
    name_id,
     
    id,
    verbatim_key,
    citation,
    status,
    locality,
    country,
    latitude,
    longitude,
    altitude,
    coordinate,
    sex,
    institution_code,
    catalog_number,
    associated_sequences,
    host,
    date,
    collector,
    reference_id,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    2217,
    NULL,
    '367353',
    'tm5YZ',
    123958,
    'male, ?Ecuador: Orellana, Tiputini Biodiversity Station nr Yasuni National Park Erwin Transect - T/2220-?m?, ?9-ii-1999male, ?Ecuador: Orellana, Tiputini Biodiversity Station nr Yasuni National Park Erwin Transect - T/2220-?m?, ?9-ii-1999?37'55"S 076?08'39"W T.L. Erwin et al Fogging terra firme forest?, EPCN.',
    'HOLOTYPE'::TYPESTATUS,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL::SEX,
    'USNM',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    10,
    10
   , now(), now()) was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00
  Where: unnamed portal parameter $6  Call getNextException to see other errors in the batch.
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:148)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:245)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:223)
	... 10 common frames omitted
Caused by: java.sql.BatchUpdateException: Batch entry 9,377 INSERT INTO type_material ( 
    dataset_key,
    sector_key,
    name_id,
     
    id,
    verbatim_key,
    citation,
    status,
    locality,
    country,
    latitude,
    longitude,
    altitude,
    coordinate,
    sex,
    institution_code,
    catalog_number,
    associated_sequences,
    host,
    date,
    collector,
    reference_id,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    2217,
    NULL,
    '367353',
    'tm5YZ',
    123958,
    'male, ?Ecuador: Orellana, Tiputini Biodiversity Station nr Yasuni National Park Erwin Transect - T/2220-?m?, ?9-ii-1999male, ?Ecuador: Orellana, Tiputini Biodiversity Station nr Yasuni National Park Erwin Transect - T/2220-?m?, ?9-ii-1999?37'55"S 076?08'39"W T.L. Erwin et al Fogging terra firme forest?, EPCN.',
    'HOLOTYPE'::TYPESTATUS,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL::SEX,
    'USNM',
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    10,
    10
   , now(), now()) was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00
  Where: unnamed portal parameter $6  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2099)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1456)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1481)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:546)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:126)
	... 14 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00
  Where: unnamed portal parameter $6
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	... 24 common frames omitted
```

**Comment by gdower** [comment]
There is a \00 in there that possibly gets interpreted as a NUL character by the importer:

9-ii-1999\00°37'55"S 076°08'39"W

**Comment by mdoering** [comment]
you're right. `\00` gets interpreted as the zero byte char. Interesting...

**Comment by mdoering** [comment]
For non ID terms the importers CsvReader unescapes various character entities such as html & xml entities, e.g. `&gt;` or xml/html tags. It also unescapes and also Java strings like \377 and \0 which causes this behavior. I will remove the later as its too unspecific.

>   A verbatim record that offers basic value cleaning and unescaping of common character entities
>   on read methods without altering the underlying original verbatim data.
>   It also strips simple xml/html tags without attributes such as <i> or </b>
>   When a value is altered during unescaping the record keeps track that it had been unescaped.
>   The following escaped character formats are recognized:
>  1) html entities
>   named &amp;
>   hex &#x0026;
>   decimal &#38;
>  2) Hexadecimal and octal escapes as used in Java, CSS & ECMA Javascript:
>   Hexadecimal unicode escapes started by  "\\u": \\u00A9 
>   Unicode code point escapes indicated by "\\u{}": \\u{2F80}
>  3) Unicode char escaping using brackets: <U+00A0>
