### ISSUE TITLE
ES exception for single char queries?

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#1331]
Found some of these in the error logs:
http://api.checklistbank.org/dataset/3LR/nameusage/search?content=SCIENTIFIC_NAME&sortBy=NAME&fuzzy=true&type=prefix&limit=20&q=festuca%20a

If you change the query `festuca%20a` to either `festuca%20` or `festuca%20ab` it works.

>life.catalogue.es.EsException: [1:434] [bool] failed to parse field [filter]. Caused by: [1:434] [bool] failed to parse field [must]
	at life.catalogue.es.EsUtil.executeRequest(EsUtil.java:373)
	at life.catalogue.es.nu.NameUsageQueryService.executeSearchRequest(NameUsageQueryService.java:91)
	at life.catalogue.es.nu.search.NameUsageSearchServiceEs.search(NameUsageSearchServiceEs.java:62)

**Comment by mdoering** [comment]
other: http://api.checklistbank.org/dataset/3LR/nameusage/search?content=SCIENTIFIC_NAME&sortBy=NAME&fuzzy=true&type=prefix&limit=20&q=rubus%20i
