### ISSUE TITLE
search is broken on dev

### ISSUE THREAD

**Issue by thomasstjerne** [CatalogueOfLife/backend#649]
https://api.dev.catalogue.life/dataset/31451/nameusage/search?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&sortBy=taxonomic

**Comment by mdoering** [comment]
```
java.lang.NullPointerException: null
	at life.catalogue.es.name.search.NameUsageSearchResponseFactory.createEnumBuckets(NameUsageSearchResponseFactory.java:127)
	at life.catalogue.es.name.search.NameUsageSearchResponseFactory.convert(NameUsageSearchResponseFactory.java:93)
	at life.catalogue.es.name.search.NameUsageSearchResponseFactory.generateFacets(NameUsageSearchResponseFactory.java:82)
	at life.catalogue.es.name.search.NameUsageSearchResponseFactory.convertEsResponse(NameUsageSearchResponseFactory.java:47)
	at life.catalogue.es.name.search.NameUsageSearchServiceEs.search(NameUsageSearchServiceEs.java:56)
	at life.catalogue.es.name.search.NameUsageSearchServiceEs.search(NameUsageSearchServiceEs.java:47)
	at life.catalogue.es.name.search.NameUsageSearchServiceEs.search(NameUsageSearchServiceEs.java:32)
```

**Comment by ayco-at-naturalis** [comment]
ouch will fix this asap (tomorrow)
