### ISSUE TITLE
Sync failure from NullPointerException

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#679]
On prod, sync silently failed in the clearinghouse-ui for dataset 1053 because of a [NullPointerException](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXFVL8-7HCKcR6PFb_mZ?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:1),query:(match:(sector:(query:1,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:9),query:(match:(attempt:(query:9,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))))):

```
java.util.NoSuchElementException: null
	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:999)
	at life.catalogue.dao.Pager$PageResultIterator.nextObj(Pager.java:159)
	at life.catalogue.dao.Pager$PageResultIterator.next(Pager.java:140)
	at life.catalogue.assembly.SectorRunnable.loadDecisions(SectorRunnable.java:158)
	at life.catalogue.assembly.SectorRunnable.init(SectorRunnable.java:115)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:82)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:31)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

The clearinghouse-ui is sending:

```JSON
POST https://api.catalogue.life/assembly/3/sync
{
  "sectorKey": 1,
  "key": 1,
  "target": {
    "id": "7b3a7eb4-e311-4521-813b-c288e408e005",
    "name": "Protozoa",
    "rank": "kingdom"
  },
  "subject": {
    "id": "x6",
    "name": "Mycetozoa",
    "rank": "phylum"
  }
}
```

Frontend version: 649f54b April 2, 2020 11:31 AM
Backend version: 3e24708 April 5, 2020 12:23 PM

**Comment by mdoering** [comment]
That is no sync but an import process that failed. The log and the POST action should not be related

**Comment by gdower** [comment]
Sorry--wrong stracktrace for a different issue. I corrected both the link and stacktrace above.

**Comment by mdoering** [comment]
good catch. A rather rare bug that only shows up when we hit decision numbers that can be devided by 100 ;)
