### ISSUE TITLE
Backend failing to delete sector due to foreign key constraint

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#699]
The backend is failing to delete [sector 3072](http://api.dev.catalogue.life/dataset/3/sector?id=3072), although it [might be reporting that it completed deletion](https://logs.gbif.org/app/kibana#/context/AWyLa2lBHCKcR6PFXu26/logs/AXG87jzHHCKcR6PFJZqp?_a=(columns:!(_source),filters:!())) because the frontend didn't throw any errors:

```
Completed SectorDelete{sectorKey=3072datasetKey=1070, sector=Sector{3072, datasetKey=3, mode=ATTACH, code=null, subjectDatasetKey=1070, subject=ORDER Mesostigmata}, created=2020-04-27T18:37:41.901793 by gdower}
```

[Stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa2lBHCKcR6PFXu26/logs/AXG87jzHHCKcR6PFJZqn?_a=(columns:!(_source),filters:!())):
```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(69035050-f853-410a-87d9-ba4f524afe1f) is still referenced from table "name_usage_3".
### The error may exist in life/catalogue/db/mapper/NameUsageMapper.xml
### The error may involve life.catalogue.db.mapper.NameUsageMapper.deleteBySector-Inline
### The error occurred while setting parameters
### SQL: DELETE FROM name_usage_3 WHERE sector_key = ?
### Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(69035050-f853-410a-87d9-ba4f524afe1f) is still referenced from table "name_usage_3".
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:212)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:72)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy125.deleteBySector(Unknown Source)
	at life.catalogue.assembly.SectorDelete.deleteSector(SectorDelete.java:84)
	at life.catalogue.assembly.SectorDelete.doWork(SectorDelete.java:42)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:89)
	at life.catalogue.assembly.SectorDelete.run(SectorDelete.java:25)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(69035050-f853-410a-87d9-ba4f524afe1f) is still referenced from table "name_usage_3".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2497)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2233)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:310)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:446)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:370)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:149)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:138)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 13 common frames omitted
```

This is a different issue from the [frontend bug report on sector deletion I opened earlier](https://github.com/CatalogueOfLife/clearinghouse-ui/issues/574).

Frontend version: b7bf159 April 27, 2020 9:30 AM
Backend version: ae2da5a April 24, 2020 10:04 PM

**Comment by gdower** [comment]
@mdoering, I figured out why. @yroskov and I had used modify tree in assembly to add the superfamily Rhodacaroidea to Order Mesostigmata (sector 3072). After I manually deleted the name Rhodacaroidea, I was able to delete sector 3072.

**Comment by mdoering** [comment]
Guess we need to block all edits while a sync is running then?

**Comment by mdoering** [comment]
Ah, you added a taxon inside an existing sector? That might indeed not be checked properly, I need to verify. Should we allow that the CoL Management Classification is patchy and not connected to the root of the tree?

**Comment by gdower** [comment]
No, I don't think we should allow attaching Management Classification below GSD attachment points. We were trying to modify the sector mapping from being attached at the order level to the family level, but deleting the sector at order level deletes the classification below that point when we really just wanted to move the sector attachment point to a lower level.

It might be easier to discuss this on the call tomorrow.

**Comment by mdoering** [comment]
It would probably be useful to mark the nodes without a sector in the assembly tree

**Comment by mdoering** [comment]
we only delete species now and keep higher taxa without a sectorKey.
