### ISSUE TITLE
Proxy database failed to sync

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#735]
For the May release, we reverted back to the ACEF version of FLOW from Annual Checklist 2019, but we could try to do the Paris checklists with proxy datasets again next month.

Here's the [stack traces](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXJTKKazHCKcR6PFzdHK?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:4485),query:(match:(sector:(query:4485,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:11),query:(match:(attempt:(query:11,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))))):

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error committing transaction.  Cause: org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.NameMapper.create (batch index #155) failed. 154 prior sub executor(s) completed successfully, but will be rolled back. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_3 ( 
    dataset_key,
    sector_key,
     
    id,
    verbatim_key,
    name_index_id,
    name_index_match_type,
    homotypic_name_id,
    scientific_name,
    scientific_name_normalized,
    authorship,
    authorship_normalized,
    rank,
    uninomial,
    genus,
    infrageneric_epithet,
    specific_epithet,
    infraspecific_epithet,
    cultivar_epithet,
    appended_phrase,
    candidatus,
    notho,
    basionym_authors,
    basionym_ex_authors,
    basionym_year,
    combination_authors,
    combination_ex_authors,
    combination_year,
    sanctioning_author,
    published_in_id,
    published_in_page,
    code,
    nom_status,
    origin,
    type,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    3,
    4485,
    'fd8308e8-9ba5-45df-97c3-0c68f6c43d7b',
    NULL,
    NULL,
    NULL::MATCHTYPE,
    NULL,
    NULL,
    '',
    NULL,
    '{}',
    'GENUS'::RANK,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FALSE',
    NULL::NAMEPART,
    '{}',
    '{}',
    NULL,
    '{}',
    '{}',
    NULL,
    NULL,
    NULL,
    NULL,
    'ZOOLOGICAL'::NOMCODE,
    NULL::NOMSTATUS,
    'IMPLICIT_NAME'::ORIGIN,
    'SCIENTIFIC'::NAMETYPE,
    NULL,
    NULL,
    102,
    102
   , now(), now()) was aborted: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).  Call getNextException to see other errors in the batch.
### Cause: org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.NameMapper.create (batch index #155) failed. 154 prior sub executor(s) completed successfully, but will be rolled back. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_3 ( 
    dataset_key,
    sector_key,
     
    id,
    verbatim_key,
    name_index_id,
    name_index_match_type,
    homotypic_name_id,
    scientific_name,
    scientific_name_normalized,
    authorship,
    authorship_normalized,
    rank,
    uninomial,
    genus,
    infrageneric_epithet,
    specific_epithet,
    infraspecific_epithet,
    cultivar_epithet,
    appended_phrase,
    candidatus,
    notho,
    basionym_authors,
    basionym_ex_authors,
    basionym_year,
    combination_authors,
    combination_ex_authors,
    combination_year,
    sanctioning_author,
    published_in_id,
    published_in_page,
    code,
    nom_status,
    origin,
    type,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    3,
    4485,
    'fd8308e8-9ba5-45df-97c3-0c68f6c43d7b',
    NULL,
    NULL,
    NULL::MATCHTYPE,
    NULL,
    NULL,
    '',
    NULL,
    '{}',
    'GENUS'::RANK,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FALSE',
    NULL::NAMEPART,
    '{}',
    '{}',
    NULL,
    '{}',
    '{}',
    NULL,
    NULL,
    NULL,
    NULL,
    'ZOOLOGICAL'::NOMCODE,
    NULL::NOMSTATUS,
    'IMPLICIT_NAME'::ORIGIN,
    'SCIENTIFIC'::NAMETYPE,
    NULL,
    NULL,
    102,
    102
   , now(), now()) was aborted: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).  Call getNextException to see other errors in the batch.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:226)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:217)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:249)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:30)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:209)
	at life.catalogue.assembly.SectorSync.sync(SectorSync.java:93)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:44)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:92)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:31)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.NameMapper.create (batch index #155) failed. 154 prior sub executor(s) completed successfully, but will be rolled back. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_3 ( 
    dataset_key,
    sector_key,
     
    id,
    verbatim_key,
    name_index_id,
    name_index_match_type,
    homotypic_name_id,
    scientific_name,
    scientific_name_normalized,
    authorship,
    authorship_normalized,
    rank,
    uninomial,
    genus,
    infrageneric_epithet,
    specific_epithet,
    infraspecific_epithet,
    cultivar_epithet,
    appended_phrase,
    candidatus,
    notho,
    basionym_authors,
    basionym_ex_authors,
    basionym_year,
    combination_authors,
    combination_ex_authors,
    combination_year,
    sanctioning_author,
    published_in_id,
    published_in_page,
    code,
    nom_status,
    origin,
    type,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    3,
    4485,
    'fd8308e8-9ba5-45df-97c3-0c68f6c43d7b',
    NULL,
    NULL,
    NULL::MATCHTYPE,
    NULL,
    NULL,
    '',
    NULL,
    '{}',
    'GENUS'::RANK,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FALSE',
    NULL::NAMEPART,
    '{}',
    '{}',
    NULL,
    '{}',
    '{}',
    NULL,
    NULL,
    NULL,
    NULL,
    'ZOOLOGICAL'::NOMCODE,
    NULL::NOMSTATUS,
    'IMPLICIT_NAME'::ORIGIN,
    'SCIENTIFIC'::NAMETYPE,
    NULL,
    NULL,
    102,
    102
   , now(), now()) was aborted: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).  Call getNextException to see other errors in the batch.
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:148)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:242)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:223)
	... 14 common frames omitted
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_3 ( 
    dataset_key,
    sector_key,
     
    id,
    verbatim_key,
    name_index_id,
    name_index_match_type,
    homotypic_name_id,
    scientific_name,
    scientific_name_normalized,
    authorship,
    authorship_normalized,
    rank,
    uninomial,
    genus,
    infrageneric_epithet,
    specific_epithet,
    infraspecific_epithet,
    cultivar_epithet,
    appended_phrase,
    candidatus,
    notho,
    basionym_authors,
    basionym_ex_authors,
    basionym_year,
    combination_authors,
    combination_ex_authors,
    combination_year,
    sanctioning_author,
    published_in_id,
    published_in_page,
    code,
    nom_status,
    origin,
    type,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    3,
    4485,
    'fd8308e8-9ba5-45df-97c3-0c68f6c43d7b',
    NULL,
    NULL,
    NULL::MATCHTYPE,
    NULL,
    NULL,
    '',
    NULL,
    '{}',
    'GENUS'::RANK,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FALSE',
    NULL::NAMEPART,
    '{}',
    '{}',
    NULL,
    '{}',
    '{}',
    NULL,
    NULL,
    NULL,
    NULL,
    'ZOOLOGICAL'::NOMCODE,
    NULL::NOMSTATUS,
    'IMPLICIT_NAME'::ORIGIN,
    'SCIENTIFIC'::NAMETYPE,
    NULL,
    NULL,
    102,
    102
   , now(), now()) was aborted: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:154)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2269)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:511)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:851)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:874)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1569)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:122)
	... 18 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	... 25 common frames omitted
```

[2](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXJTKKazHCKcR6PFzdHL?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:4485),query:(match:(sector:(query:4485,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:11),query:(match:(attempt:(query:11,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))))):
```
Sector Sync 4485 failed: life.catalogue.db.mapper.NameMapper.create (batch index #155) failed. 154 prior sub executor(s) completed successfully, but will be rolled back. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_3 ( 
    dataset_key,
    sector_key,
     
    id,
    verbatim_key,
    name_index_id,
    name_index_match_type,
    homotypic_name_id,
    scientific_name,
    scientific_name_normalized,
    authorship,
    authorship_normalized,
    rank,
    uninomial,
    genus,
    infrageneric_epithet,
    specific_epithet,
    infraspecific_epithet,
    cultivar_epithet,
    appended_phrase,
    candidatus,
    notho,
    basionym_authors,
    basionym_ex_authors,
    basionym_year,
    combination_authors,
    combination_ex_authors,
    combination_year,
    sanctioning_author,
    published_in_id,
    published_in_page,
    code,
    nom_status,
    origin,
    type,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    3,
    4485,
    'fd8308e8-9ba5-45df-97c3-0c68f6c43d7b',
    NULL,
    NULL,
    NULL::MATCHTYPE,
    NULL,
    NULL,
    '',
    NULL,
    '{}',
    'GENUS'::RANK,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FALSE',
    NULL::NAMEPART,
    '{}',
    '{}',
    NULL,
    '{}',
    '{}',
    NULL,
    NULL,
    NULL,
    NULL,
    'ZOOLOGICAL'::NOMCODE,
    NULL::NOMSTATUS,
    'IMPLICIT_NAME'::ORIGIN,
    'SCIENTIFIC'::NAMETYPE,
    NULL,
    NULL,
    102,
    102
   , now(), now()) was aborted: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).  Call getNextException to see other errors in the batch.
```

[3](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXJTKKazHCKcR6PFzdHL?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:4485),query:(match:(sector:(query:4485,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:11),query:(match:(attempt:(query:11,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))))):
```
org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.NameMapper.create (batch index #155) failed. 154 prior sub executor(s) completed successfully, but will be rolled back. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_3 ( 
    dataset_key,
    sector_key,
     
    id,
    verbatim_key,
    name_index_id,
    name_index_match_type,
    homotypic_name_id,
    scientific_name,
    scientific_name_normalized,
    authorship,
    authorship_normalized,
    rank,
    uninomial,
    genus,
    infrageneric_epithet,
    specific_epithet,
    infraspecific_epithet,
    cultivar_epithet,
    appended_phrase,
    candidatus,
    notho,
    basionym_authors,
    basionym_ex_authors,
    basionym_year,
    combination_authors,
    combination_ex_authors,
    combination_year,
    sanctioning_author,
    published_in_id,
    published_in_page,
    code,
    nom_status,
    origin,
    type,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    3,
    4485,
    'fd8308e8-9ba5-45df-97c3-0c68f6c43d7b',
    NULL,
    NULL,
    NULL::MATCHTYPE,
    NULL,
    NULL,
    '',
    NULL,
    '{}',
    'GENUS'::RANK,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FALSE',
    NULL::NAMEPART,
    '{}',
    '{}',
    NULL,
    '{}',
    '{}',
    NULL,
    NULL,
    NULL,
    NULL,
    'ZOOLOGICAL'::NOMCODE,
    NULL::NOMSTATUS,
    'IMPLICIT_NAME'::ORIGIN,
    'SCIENTIFIC'::NAMETYPE,
    NULL,
    NULL,
    102,
    102
   , now(), now()) was aborted: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).  Call getNextException to see other errors in the batch.
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:148)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:242)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:223)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:217)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:249)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:30)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:209)
	at life.catalogue.assembly.SectorSync.sync(SectorSync.java:93)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:44)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:92)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:31)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_3 ( 
    dataset_key,
    sector_key,
     
    id,
    verbatim_key,
    name_index_id,
    name_index_match_type,
    homotypic_name_id,
    scientific_name,
    scientific_name_normalized,
    authorship,
    authorship_normalized,
    rank,
    uninomial,
    genus,
    infrageneric_epithet,
    specific_epithet,
    infraspecific_epithet,
    cultivar_epithet,
    appended_phrase,
    candidatus,
    notho,
    basionym_authors,
    basionym_ex_authors,
    basionym_year,
    combination_authors,
    combination_ex_authors,
    combination_year,
    sanctioning_author,
    published_in_id,
    published_in_page,
    code,
    nom_status,
    origin,
    type,
    link,
    remarks,
    created_by,
    modified_by
   
   , created, modified)
    VALUES ( 
    3,
    4485,
    'fd8308e8-9ba5-45df-97c3-0c68f6c43d7b',
    NULL,
    NULL,
    NULL::MATCHTYPE,
    NULL,
    NULL,
    '',
    NULL,
    '{}',
    'GENUS'::RANK,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    'FALSE',
    NULL::NAMEPART,
    '{}',
    '{}',
    NULL,
    '{}',
    '{}',
    NULL,
    NULL,
    NULL,
    NULL,
    'ZOOLOGICAL'::NOMCODE,
    NULL::NOMSTATUS,
    'IMPLICIT_NAME'::ORIGIN,
    'SCIENTIFIC'::NAMETYPE,
    NULL,
    NULL,
    102,
    102
   , now(), now()) was aborted: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:154)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2269)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:511)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:851)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:874)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1569)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:122)
	... 18 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "scientific_name" violates not-null constraint
  Detail: Failing row contains (fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, f, 3, 4485, null, null, GENUS, null, ZOOLOGICAL, null, IMPLICIT_NAME, SCIENTIFIC, 102, 102, 2020-05-26 22:44:26.578641, 2020-05-26 22:44:26.578641, fd8308e8-9ba5-45df-97c3-0c68f6c43d7b, null, null, , null, {}, null, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	... 25 common frames omitted
```

**Comment by gdower** [comment]
I setup the [proxy dataset](https://data.dev.catalogue.life/catalogue/3/dataset/1011/issues) on dev and was able to [reproduce it](https://logs.gbif.org/app/kibana#/discover?_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:sector,negate:!f,type:phrase,value:'20004'),query:(match:(sector:(query:20004,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:AWyLa2lBHCKcR6PFXu26,key:environment,negate:!f,type:phrase,value:col-dev),query:(match:(environment:(query:col-dev,type:phrase))))),index:AWyLa2lBHCKcR6PFXu26,interval:auto,query:(match_all:()),sort:!('@timestamp',desc))).

**Comment by gdower** [comment]
[Sector sync worked for COOL as a proxy dataset](https://data.dev.catalogue.life/catalogue/3/sector/sync?limit=25&offset=0&sectorKey=20005), so it's got to be a specific problem with the FLOW proxy dataset likely caused by a missing a scientific name. I tried blocking the scientific name in FLOW with a missing genus but that didn't work.

**Comment by mdoering** [comment]
Weird, how can there be no scientific name? That obviously should not happen, I'm digging in

**Comment by mdoering** [comment]
The problematic name is an "implicit" name, i.e. either a genus, subgenus or species that is created because it is missing in the source when a species or infraspecific taxon is copied. This makes sure we always have a genus or species for infraspecifics.

Not sure which record exactly yet and why that has no scientific_name, but I made sure now that implicit names do actually have a name ;)

**Comment by mdoering** [comment]
think I found it:

```
  id   | pid |  status  |  rank   |    prank    |    scientific_name     |            pname             
-------+-----+----------+---------+-------------+------------------------+------------------------------
 18849 | xHJ | ACCEPTED | SPECIES | FAMILY      | Ormenis devincta       | . Fulgoroidea incertae sedis
 18872 | xHJ | ACCEPTED | SPECIES | FAMILY      | Asiraca albipuncta     | . Fulgoroidea incertae sedis
 18871 | xHJ | ACCEPTED | SPECIES | FAMILY      | Asiraca tertiara       | . Fulgoroidea incertae sedis
 22451 | xC  | ACCEPTED | SPECIES | SUPERFAMILY | ? ocellatum            | Fulgoroidea
 18933 | xKL | ACCEPTED | SPECIES | FAMILY      | Aphaena rotundipennis  | Nogodinidae
 18934 | xKL | ACCEPTED | SPECIES | FAMILY      | Paralatindia saussurei | Nogodinidae
```

`? ocellatum` has no genus, but is a "species" with a superfamily parent. Hence the sync tries to create the missing genus. That is NULL in this case and off the exception goes.

I am catching those cases now and log a warning in kibana.

**Comment by mdoering** [comment]
@yroskov @gdower blocking that very name should allow to sync even with the old code on prod

**Comment by mdoering** [comment]
Hm, I just see you already have it blocked

**Comment by mdoering** [comment]
deployed to both dev and prod. Seems to work on dev!
