### ISSUE TITLE
`IllegalArgumentException: Taxa cannot have a synonym status` on sector sync

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#780]
[Sector sync for Polypodiales in World Ferns failed](https://github.com/CatalogueOfLife/data/issues/146#issuecomment-655140511) because of `IllegalArgumentException: Taxa cannot have a synonym status`. However, there is no synonym status in the data within the Taxon table.

Here's the [stacktrace](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXMmEfJgHCKcR6PF77qY?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:115576),query:(match:(sector:(query:115576,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-24h,mode:quick,to:now))):

```
org.apache.ibatis.reflection.ReflectionException: Could not set property 'status' of 'class life.catalogue.api.model.Taxon' with value 'SYNONYM' Cause: java.lang.IllegalArgumentException: Taxa cannot have a synonym status
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:185)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.set(BeanWrapper.java:59)
	at org.apache.ibatis.reflection.MetaObject.setValue(MetaObject.java:140)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:527)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:903)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForNestedResultMap(DefaultResultSetHandler.java:870)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:326)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy177.foreignChildren(Unknown Source)
	at life.catalogue.assembly.SectorRunnable.loadForeignChildren(SectorRunnable.java:180)
	at life.catalogue.assembly.SectorRunnable.init(SectorRunnable.java:129)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:89)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Taxa cannot have a synonym status
	at life.catalogue.api.model.Taxon.setStatus(Taxon.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor368.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:44)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:180)
	... 29 common frames omitted
```

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.apache.ibatis.reflection.ReflectionException: Could not set property 'status' of 'class life.catalogue.api.model.Taxon' with value 'SYNONYM' Cause: java.lang.IllegalArgumentException: Taxa cannot have a synonym status
### The error may exist in life/catalogue/db/mapper/TaxonMapper.xml
### The error may involve life.catalogue.db.mapper.TaxonMapper.foreignChildren
### The error occurred while handling results
### SQL: SELECT                       u.id AS id,     u.dataset_key AS dataset_key,     u.sector_key AS sector_key,     u.verbatim_key AS verbatim_key,     u.status AS status,     u.origin AS origin,     u.parent_id AS parent_id,     u.name_phrase AS name_phrase,     u.according_to_id AS according_to_id,     u.reference_ids AS reference_ids,     u.remarks AS remarks,     u.created AS created,     u.created_by AS created_by,     u.modified AS modified,     u.modified_by AS modified_by    ,     u.scrutinizer AS scrutinizer,     u.scrutinizer_date AS scrutinizer_date,     u.extinct AS extinct,     u.temporal_range_start AS temporal_range_start,     u.temporal_range_end AS temporal_range_end,     u.lifezones AS lifezones,     u.link AS link    ,     r.citation AS according_to,                 n.id AS n_id,     n.scientific_name AS n_scientific_name,     n.authorship AS n_authorship,     n.rank AS n_rank,     n.uninomial AS n_uninomial,     n.genus AS n_genus,     n.infrageneric_epithet AS n_infrageneric_epithet,     n.specific_epithet AS n_specific_epithet,     n.infraspecific_epithet AS n_infraspecific_epithet,     n.cultivar_epithet AS n_cultivar_epithet,     n.candidatus AS n_candidatus,     n.notho AS n_notho,     n.basionym_authors AS n_basionym_authors,     n.basionym_ex_authors AS n_basionym_ex_authors,     n.basionym_year AS n_basionym_year,     n.combination_authors AS n_combination_authors,     n.combination_ex_authors AS n_combination_ex_authors,     n.combination_year AS n_combination_year,     n.sanctioning_author AS n_sanctioning_author,     n.code AS n_code,     n.nomenclatural_note AS n_nomenclatural_note,     n.unparsed AS n_unparsed    ,     n.dataset_key AS n_dataset_key,     n.sector_key AS n_sector_key,     n.verbatim_key AS n_verbatim_key,     n.name_index_id AS n_name_index_id,     n.name_index_match_type AS n_name_index_match_type,     n.homotypic_name_id AS n_homotypic_name_id,     n.published_in_id AS n_published_in_id,     n.published_in_page AS n_published_in_page,     n.nom_status AS n_nom_status,     n.origin AS n_origin,     n.type AS n_type,     n.link AS n_link,     n.remarks AS n_remarks,     n.created AS n_created,     n.created_by AS n_created_by,     n.modified AS n_modified,     n.modified_by AS n_modified_by    ,     (SELECT count(*) FROM name_usage_3 WHERE parent_id=u.id) AS child_count         FROM           name_usage_3 u JOIN name_3 n ON u.name_id=n.id     LEFT JOIN reference_3 r ON u.according_to_id=r.id         JOIN name_usage_3 p ON p.id=u.parent_id     WHERE p.sector_key=?     AND u.sector_key!=?
### Cause: org.apache.ibatis.reflection.ReflectionException: Could not set property 'status' of 'class life.catalogue.api.model.Taxon' with value 'SYNONYM' Cause: java.lang.IllegalArgumentException: Taxa cannot have a synonym status
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:149)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:140)
	at org.apache.ibatis.binding.MapperMethod.executeForMany(MapperMethod.java:147)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:80)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy177.foreignChildren(Unknown Source)
	at life.catalogue.assembly.SectorRunnable.loadForeignChildren(SectorRunnable.java:180)
	at life.catalogue.assembly.SectorRunnable.init(SectorRunnable.java:129)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:89)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.ibatis.reflection.ReflectionException: Could not set property 'status' of 'class life.catalogue.api.model.Taxon' with value 'SYNONYM' Cause: java.lang.IllegalArgumentException: Taxa cannot have a synonym status
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:185)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.set(BeanWrapper.java:59)
	at org.apache.ibatis.reflection.MetaObject.setValue(MetaObject.java:140)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.applyAutomaticMappings(DefaultResultSetHandler.java:527)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.getRowValue(DefaultResultSetHandler.java:903)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValuesForNestedResultMap(DefaultResultSetHandler.java:870)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleRowValues(DefaultResultSetHandler.java:326)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSet(DefaultResultSetHandler.java:301)
	at org.apache.ibatis.executor.resultset.DefaultResultSetHandler.handleResultSets(DefaultResultSetHandler.java:194)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.query(PreparedStatementHandler.java:65)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.query(RoutingStatementHandler.java:79)
	at org.apache.ibatis.executor.SimpleExecutor.doQuery(SimpleExecutor.java:63)
	at org.apache.ibatis.executor.BaseExecutor.queryFromDatabase(BaseExecutor.java:324)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:156)
	at org.apache.ibatis.executor.BaseExecutor.query(BaseExecutor.java:136)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.selectList(DefaultSqlSession.java:147)
	... 14 common frames omitted
Caused by: java.lang.IllegalArgumentException: Taxa cannot have a synonym status
	at life.catalogue.api.model.Taxon.setStatus(Taxon.java:46)
	at jdk.internal.reflect.GeneratedMethodAccessor368.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.ibatis.reflection.invoker.MethodInvoker.invoke(MethodInvoker.java:44)
	at org.apache.ibatis.reflection.wrapper.BeanWrapper.setBeanProperty(BeanWrapper.java:180)
	... 29 common frames omitted
```

**Comment by mdoering** [comment]
This is interesting. The method TaxonMapper.foreignChildren list all immediate child taxa that originated from a different sector then the one we are about to sync. This is needed to temporarily move these taxa while we sync and at the end of a sync move them back again.

I always thought these child taxa have to be accepted taxa. But in this case we see there is also a synonym `Neurosoria` from sector `115582`. The mapper is not prepared to deal with that. I wonder if we need to be prepared to deal also with synonyms or whether the synonym itself is already wrong.

**Comment by mdoering** [comment]
[Neurosoria Mett. ex Kuhn](https://data.catalogue.life/catalogue/3/names?facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0&q=Neurosoria&sortBy=taxonomic) synonym of [Cheilanthes Sw.](https://data.catalogue.life/catalogue/3/taxon/37fad12d-b6e4-44a1-9ef4-7b3fb332ee09)

So these are the split genus union sectors. And I guess for a union it makes sense to also include synonyms that are linked directly to the target taxon.

I will update `foreignChildren` to also deal with synonyms then

**Comment by mdoering** [comment]
I have triggered a new sync after the fix was deployed to prod

**Comment by mdoering** [comment]
synced fine!
