### ISSUE TITLE
Sync failures: "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#782]
We're syncing all sectors right now, and the vast majority are succeeding, but [some are failing](https://data.catalogue.life/catalogue/3/sector/sync?limit=25&offset=0&state=failed) with the following foreign key constraint error.

[Logs](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXM4jOPiHCKcR6PFTqDi?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:6941),query:(match:(sector:(query:6941,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:5),query:(match:(attempt:(query:5,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))),predecessorCount:5,sort:!('@timestamp',desc),successorCount:5)&_g=(refreshInterval:(display:On,pause:!f,value:0),time:(from:now-4h,mode:quick,to:now))):
```
org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(61986195-4563-4f14-a0f2-fcd7dcc0b830) is still referenced from table "name_usage_3".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:148)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:212)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:72)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy129.deleteBySector(Unknown Source)
	at life.catalogue.assembly.SectorSync.deleteOld(SectorSync.java:240)
	at life.catalogue.assembly.SectorSync.sync(SectorSync.java:92)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:46)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:90)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(61986195-4563-4f14-a0f2-fcd7dcc0b830) is still referenced from table "name_usage_3".
### The error may exist in life/catalogue/db/mapper/NameUsageMapper.xml
### The error may involve life.catalogue.db.mapper.NameUsageMapper.deleteBySector-Inline
### The error occurred while setting parameters
### SQL: DELETE FROM name_usage_3 WHERE sector_key = ?
### Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(61986195-4563-4f14-a0f2-fcd7dcc0b830) is still referenced from table "name_usage_3".
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.delete(DefaultSqlSession.java:212)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:72)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy129.deleteBySector(Unknown Source)
	at life.catalogue.assembly.SectorSync.deleteOld(SectorSync.java:240)
	at life.catalogue.assembly.SectorSync.sync(SectorSync.java:92)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:46)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:90)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(61986195-4563-4f14-a0f2-fcd7dcc0b830) is still referenced from table "name_usage_3".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:448)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:369)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:159)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:148)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 14 common frames omitted
```

**Comment by mdoering** [comment]
Hm, that is exactly the error the temporary moving of taxa is supposed to avoid.
I'll check the cause

**Comment by gdower** [comment]
Maybe it's because there are CoL management classification sectors nested within some of the ITIS sectors? I haven't checked all of them yet, but it seems to be a shared pattern:

http://www.catalogueoflife.org/col/browse/tree/id/aa8136d28ad8eedabaf8bf1d77c92d8d
http://www.catalogueoflife.org/col/browse/tree/id/c891cc6f0aa79ab199a0ba6f9400c42e
http://www.catalogueoflife.org/col/browse/tree/id/44b8b8bbbb319dfb60ff24c7a55a6c22
http://www.catalogueoflife.org/col/browse/tree/id/a357f590771cefaa08786701892fdccd

If that's the issue, we might be able to re-arrange the sectors to fix it, but let me discuss it with @yroskov.

**Comment by mdoering** [comment]
very likely indeed! I probably only look for other non null sectors

**Comment by mdoering** [comment]
Takes -3h to get onto prod, I leave a short notice here when its ready

**Comment by gdower** [comment]
Is deploying in the middle of syncing alright? I guess it might potentially only mess up the sector currently being synced during deployment, unless syncing is done with transactions? At present we have 300 of 699 syncs queued and I started it yesterday night, so it will probably still take roughly 8-9 hours to finish (but it's difficult to estimate because of the variable sector sizes).

We likely are going to re-arrange these sectors because we shouldn't have management classification embedded within a GSD.

**Comment by mdoering** [comment]
No, not the best idea. If I deploy during syncs the remaining syncs will be canceled.
Please leave me a note here when you are done and it will be fine to update prod.

I might have to wait until thursday when Im back.

**Comment by gdower** [comment]
Go ahead with the deployment. As soon as that is done, I'll kick off the sync all again and it can just run over the weekend. I think I'll still be able to get a testing conversion done by Monday or Tuesday.

**Comment by mdoering** [comment]
deployed
