### ISSUE TITLE
Importer and sync failure: ClassCastException

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#785]
[Syncing Opiliones failed](https://data.catalogue.life/catalogue/3/sector/sync?limit=25&offset=0&state=failed) with a [ClassCastException](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXNIjC7MHCKcR6PFaH69?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:3064),query:(match:(sector:(query:3064,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:6),query:(match:(attempt:(query:6,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))))):

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at life.catalogue.dao.NamesTreeDao$NamesIdWriter.accept(NamesTreeDao.java:116)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.dao.NamesTreeDao.updateSectorNames(NamesTreeDao.java:71)
	at life.catalogue.assembly.SectorSync.metrics(SectorSync.java:80)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:47)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:90)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:33)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gdower** [comment]
This same bug is [breaking the importer](https://data.catalogue.life/imports/finished?limit=10&offset=0) on prod. I think it is a separate issue from what @thomasstjerne reported in #784, which seems to be a problem with the names index being shared between prod and dev.

[Logs](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXNOD8lTHCKcR6PFso_x?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:level,negate:!t,type:phrase,value:DEBUG),query:(match:(level:(query:DEBUG,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:level,negate:!t,type:phrase,value:INFO),query:(match:(level:(query:INFO,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:dataset,negate:!f,type:phrase,value:'2147'),query:(match:(dataset:(query:'2147',type:phrase))))))):

```
java.lang.ClassCastException: class java.lang.String cannot be cast to class java.lang.Integer (java.lang.String and java.lang.Integer are in module java.base of loader 'bootstrap')
	at life.catalogue.dao.NamesTreeDao$NamesIdWriter.accept(NamesTreeDao.java:116)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.dao.NamesTreeDao.updateDatasetNames(NamesTreeDao.java:54)
	at life.catalogue.dao.DatasetImportDao.updateMetrics(DatasetImportDao.java:124)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:242)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:118)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mdoering** [comment]
fixed in https://github.com/CatalogueOfLife/backend/commit/93a4171f4faecea063fcedd9feeb6ee2e0fb4b3d
