### ISSUE TITLE
Nested sector failing to sync due to IllegalStateException: Blocked usage x59E should not have been traversed

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#792]
Sync of the nested sector Cicadellidae is failing with the following [IllegalStateException](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXOWuuP5HCKcR6PFuQ8D?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:60919),query:(match:(sector:(query:60919,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:8),query:(match:(attempt:(query:8,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))))) exception:

```
java.lang.IllegalStateException: Blocked usage x59E should not have been traversed
	at life.catalogue.assembly.TreeCopyHandler.applyDecision(TreeCopyHandler.java:286)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:218)
	at life.catalogue.assembly.TreeCopyHandler.accept(TreeCopyHandler.java:30)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:248)
	at life.catalogue.assembly.SectorSync.sync(SectorSync.java:118)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:47)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:90)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:34)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

This sector has 2 GSDs union joined on the Cicadellidae family with sectorKey 60919 failing to sync:

http://api.catalogue.life/dataset/3/sector?name=Cicadellidae

There is a [block decision on `x59E`](
https://data.catalogue.life/catalogue/3/dataset/1189/workbench?decisionMode=_NOT_NULL&facet=rank&facet=issue&facet=status&facet=nomstatus&facet=type&facet=field&limit=50&offset=0) and perhaps it is not needed now based on the changes made by @mdoering for nested sectors not needing blocks anymore? For now I'm going to leave it as is, although removing that decision and syncing will probably fix the [missing accepted species and synonyms](https://github.com/CatalogueOfLife/data/issues/157#issuecomment-661951544) found by @yroskov.

**Comment by mdoering** [comment]
I am syncinc i3 Cicadellidae right now, works with the fix. A rare bug well spotted, @gdower !
