### ISSUE TITLE
Sector delete fails: update or delete on table "name_usage_3" violates foreign key constraint

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#806]
Sector delete returns a 204 response code, but [fails](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXPu7iTrHCKcR6PFzc3c?_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:sector,negate:!f,type:phrase,value:766),query:(match:(sector:(query:766,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:attempt,negate:!f,type:phrase,value:6),query:(match:(attempt:(query:6,type:phrase)))),('$state':(store:appState),meta:(alias:!n,disabled:!t,index:AWyLa4mQHCKcR6PFXu4X,key:environment,negate:!f,type:phrase,value:col-prod),query:(match:(environment:(query:col-prod,type:phrase))))))):

https://data.catalogue.life/catalogue/3/names?q=Histeridae&SECTOR_DATASET_KEY=2028

Please note that the sector we are trying to delete is in dataset 2028, not 2144. Possibly related, we get an error that eccb97f3-8706-4286-9cfd-94df85a92a1e does not exist when searching for Histeridae in assembly search.

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error committing transaction.  Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(c53e24ee-e832-4e73-b08e-3531f6047552) is still referenced from table "name_usage_3".
### Cause: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(c53e24ee-e832-4e73-b08e-3531f6047552) is still referenced from table "name_usage_3".
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:226)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:217)
	at life.catalogue.assembly.SectorDelete.deleteSector(SectorDelete.java:65)
	at life.catalogue.assembly.SectorDelete.doWork(SectorDelete.java:41)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:88)
	at life.catalogue.assembly.SectorDelete.run(SectorDelete.java:26)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "name_usage_3" violates foreign key constraint "name_usage_3_parent_id_fk" on table "name_usage_3"
  Detail: Key (id)=(c53e24ee-e832-4e73-b08e-3531f6047552) is still referenced from table "name_usage_3".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2533)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2268)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:313)
	at org.postgresql.jdbc.PgConnection.executeTransactionCommand(PgConnection.java:829)
	at org.postgresql.jdbc.PgConnection.commit(PgConnection.java:851)
	at com.zaxxer.hikari.pool.ProxyConnection.commit(ProxyConnection.java:365)
	at com.zaxxer.hikari.pool.HikariProxyConnection.commit(HikariProxyConnection.java)
	at org.apache.ibatis.transaction.jdbc.JdbcTransaction.commit(JdbcTransaction.java:71)
	at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:244)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:223)
	... 10 common frames omitted
```

Frontend version: 748f62f August 14, 2020 4:56 AM
Backend version: 9b67c47 August 12, 2020 6:42 AM

**Comment by gdower** [comment]
After registering a new Histeridae sector from 2144 replacing the sector from 2028, I was able to successfully delete the 2028 sector. Now searching for Histeridae in assembly search does not result in the error that eccb97f3-8706-4286-9cfd-94df85a92a1e is missing.

**Comment by gdower** [comment]
I don't know if this will be reproducible or not, so I'm closing it for now. I'll reopen it if we hit the same issue again.

**Comment by mdoering** [comment]
maybe the same as #800 and #802?
The fix is not yet deployed to prod, just manually cured for Arachnida
