### ISSUE TITLE
Cannot deserialize instance of `java.util.ArrayList<life.catalogue.api.model.ParserConfig>`

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#844]
I'm getting the following error while trying to configure the name parser with:

POST /parser/name/config
```
{
      "id": "Jezzinothrips cretacicus|zur Strassen, 1973",
      "scientificName": "Jezzinothrips cretacicus",
      "authorship": "zur Strassen, 1973",
      "rank": "species",
      "genus": "Jezzinothrips",
      "specificEpithet": "cretacicus",
      "combinationAuthorship": {
        "authors": [
          "zur Strassen"
        ],
        "year": "1973"
      },
      "code": "zoological",
      "type": "scientific"
}
```
I did make a mistake initially and deleted a name parser config with the id `Jezzinothrips cretacicus|zur Strassen, 1973`. 

[Logs](https://logs.gbif.org/app/kibana#/context/AWyLa4mQHCKcR6PFXu4X/logs/AXR_G0a4HCKcR6PFANVU?_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!())):
```
com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.util.ArrayList<life.catalogue.api.model.ParserConfig>` out of START_OBJECT token
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1442)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1216)
	at com.fasterxml.jackson.databind.DeserializationContext.handleUnexpectedToken(DeserializationContext.java:1168)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.handleNonArray(CollectionDeserializer.java:332)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:265)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:245)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:27)
	at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1682)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:977)
	at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:814)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:877)
	at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:274)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:73)
	at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:56)
	at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50)
	at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:68)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
	at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1617)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
	at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:545)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:249)
	at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:717)
	at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by gdower** [comment]
There's going to need to be a ton of zur Strassen corrections, unless there is a better way to get the name parser to recognize zur as part of the surname.

**Comment by mdoering** [comment]
I look into the bug on tuesday.

As for `zur Strassen`: if you create one parser config which includes an authorship, the parser gets configured for that authorship in any other names too. But only if the authorship was given explicitly which is probably the case for us. So if the author is the only problem try with just a single config.

But I should also improve the parser properly to recognize this case - will do this on tuesday too.
If you find these cases please log an issue with the name parser!

**Comment by mdoering** [comment]
A family of taxonomists: https://de.wikipedia.org/wiki/Otto_zur_Strassen

**Comment by gdower** [comment]
So something like this for the parser config?

```
{
      "id": "|zur Strassen",
      "authorship": "zur Strassen"
}
```
I get the same deserialization error when trying to post that to dev:

```
{
  "code": 400,
  "message": "Cannot deserialize instance of `java.util.ArrayList<life.catalogue.api.model.ParserConfig>` out of START_OBJECT token\n at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 1]"
}
```

**Comment by mdoering** [comment]
Urf, this is simply because the API expects a LIST of config objects to be posted.
Not very intuitive indeed. But I though it is important to be able to post many in one go. 
Maybe thats not really needed or should rather have a dedicated method.

Try to post an array - it worked on dev!

And please always post some full name, not just the authorship alone.
The author will be stored separately in any case.

**Comment by gdower** [comment]
Could you please give an example of how to configure the parser for author strings? For example, I posted this config to dev:

```
[{
      "id": "Jezzinothrips cretacicus|zur Strassen, 1973",
      "scientificName": "Jezzinothrips cretacicus",
      "authorship": "zur Strassen, 1973",
      "rank": "species",
      "genus": "Jezzinothrips",
      "specificEpithet": "cretacicus",
      "combinationAuthorship": {
        "authors": [
          "zur Strassen"
        ],
        "year": "1973"
      },
      "code": "zoological",
      "type": "scientific"
}]
```
which gave me a 201, but I still get the wrong output for zur Strassen for a different scientific name:

https://api.dev.catalogue.life/parser/name?name=Aus%20bus%20zur%20Strassen,%201973&code=zoological

```
[
  {
    "name": {
      "nameIndexIds": [],
      "scientificName": "Aus bus zur",
      "authorship": "Strassen, 1973",
      "rank": "infraspecific name",
      "genus": "Aus",
      "specificEpithet": "bus",
      "infraspecificEpithet": "zur",
      "combinationAuthorship": {
        "authors": [
          "Strassen"
        ],
        "year": "1973"
      },
      "code": "zoological",
      "type": "scientific",
      "parsed": true
    },
    "extinct": false
  }
]
```

I can provide a full name parser config for all zur Strassen names, if needed, but if there's a way to configure author strings generically for all zur Strassen names that would probably be better.

**Comment by mdoering** [comment]
It only works if you give the authorship separate in 2 fields (scientificName & authorship).
If i'ts part of the scientificName the parser cannot apply the authorship configs alone.
But I see we do not allow the authorship to be given separately in the parser API, I will add that. The importer uses the explicit authorship if given via ColDP or DwC

**Comment by mdoering** [comment]
This works now locally:
http://localhost:8080/parser/name?name=Jezzinothrips%20cretacicus&authorship=zur%20Strassen,%201973

```
{
  "name": {
    "nameIndexIds": [],
    "scientificName": "Jezzinothrips cretacicus",
    "authorship": "zur Strassen, 1973",
    "rank": "species",
    "genus": "Jezzinothrips",
    "specificEpithet": "cretacicus",
    "combinationAuthorship": {
      "authors": [
        "zur Strassen, 1973"
      ]
    },
    "type": "scientific",
    "parsed": true
  },
  "extinct": false,
  "issues": [
    "unparsable name",
    "unparsable authorship"
  ]
}
```

**Comment by gdower** [comment]
Ah, that makes sense.

I tried:

```
[{
      "id": "|zur Strassen",
      "scientificName": "zur Strassen",
      "authorship": "zur Strassen"
}]
```

And I get a constraint error on rank not being allowed to be null, which is probably what you meant.

```
{
  "code": 400,
  "message": "Database constraint violation",
  "details": "### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: null value in column \"rank\" violates not-null constraint\n  Detail: Failing row contains (|zur Strassen, f, f, null, null, null, null, 104, 2020-09-14 21:15:41.943093, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null, null).\n### The error may exist in life/catalogue/db/mapper/ParserConfigMapper.xml\n### The error may involve life.catalogue.db.mapper.ParserConfigMapper.create-Inline\n### The error occurred while setting parameters\n### SQL: INSERT INTO parser_config (      id,     rank,     uninomial,     genus,     infrageneric_epithet,     specific_epithet,     infraspecific_epithet,     cultivar_epithet,     candidatus,     notho,     basionym_authors,     basionym_ex_authors,     basionym_year,     combination_authors,     combination_ex_authors,     combination_year,     sanctioning_author,     code,     type,     nomenclatural_note,     taxonomic_note,     created_by    , created)     VALUES (      ?,     ?::RANK,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?::NAMEPART,     ?,     ?,     ?,     ?,     ?,     ?,     ?,     ?::NOMCODE,     ?::NAMETYPE,     ?,     ?,     ?    , now())\n### Cause: org.postgresql.util.PSQLException: ERROR: null value in column \"rank\" violates not-null constraint\n  Detail: Failing row contains (|zur Strassen, f, f, null, null, null, null, 104, 2020-09-14 21:15:41.943093, null, null, null, null, null, null, {}, {}, null, {}, {}, null, null, null, null, null, null, null)."
}
```
