### ISSUE TITLE
Elasticsearch batch indexing fails without error

### ISSUE THREAD

**Issue by mdoering** [CatalogueOfLife/backend#863]
Using the NameUsageIndexServiceEs to index a dataset sometimes does not index all records.
There are no exceptions and the counter reports all records just fine. But the ES index does not contain all rows.

Digging into ES logs reveals there are indeed ES exceptions occurring (see below for larger stacktrace).

> StrictDynamicMappingException: mapping set to strict, dynamic introduction of [nameIndexId] within [_doc] is not allowed

This one is based on an outdated index definition that can be fixed by creating a new index.

@ayco-at-naturalis Is there an option for the batch client to be aware of these errors and report them back, i.e. throw an indexing exception?

```
[2020-10-02T11:28:33,577][DEBUG][o.e.a.b.TransportShardBulkAction] [node-coldev] [dev-nu][0] failed to execute bulk item (index) index {[dev-nu][_doc][M7MS6XQBfBi8UciVIHg6], source[{"usageId":"757842","datasetKey":1106,"scientificName":"Goniocidaris (Cyrtocidaris) tenuispina var. tuberculata","nameStrings":{"sciNameLetter":"g","genusLetter":"g","genusOrMonomial":["goniocidaris"],"specificEpithet":["tenuispina"],"infraspecificEpithet":["tuberculata"]},"authorship":["Mortensen"],"authorshipYear":["1927"],"authorshipComplete":"Mortensen, 1927","nameId":"757842","nameIndexId":1672787,"rank":74,"type":0,"nomCode":5,"nameFields":[1,2,3,4,11,13,15],"status":2,"issues":[36],"classificationIds":["x4","x6","x8","xA","x5G","x5J","x3KC","x3KL","513291","513658","757842"],"classification":[{"rank":4,"name":"Animalia"},{"rank":8,"name":"Echinodermata"},{"rank":12,"name":"Echinoidea"},{"rank":33,"name":"Cidaroida"},{"rank":42,"name":"Cidaroidea"},{"rank":44,"name":"Cidaridae"},{"rank":52,"name":"Goniocidaris"},{"rank":53,"name":"Cyrtocidaris"},{"rank":63,"name":"Goniocidaris (Cyrtocidaris) tenuispina"},{"rank":64,"name":"Goniocidaris (Cyrtocidaris) tenuispina tuberculata"},{"rank":74,"name":"Goniocidaris (Cyrtocidaris) tenuispina var. tuberculata"}],"acceptedName":"Goniocidaris (Cyrtocidaris) tenuispina tuberculata","payload":"eJzlkktv2zAQhP9KwENPjC3KetgCgjZ9oAiC9JLcihxoam0tapEEScV2Df/3LpXYsZumTVGgPfQo6ltyZnY2DGtWsTIvx1nKOOu8nAOrNuwNnV7TgXIgAxDzOU3ShIuEpzzjWc4FT5OxKESSJLd77O2aVYSw1tQ4w1+P7bjd3B24qQzYXkJ/kBU5Z1q2vaJnlGQ8n/Ayz4rx5LekPJl7iZbGtCasLapPJOriKLko80LXsLqSQTU3a0uiR5zJLjTG+QYtwVfGBdAeND8Rk7SkKSf1F1aVGWdz0J0n5qPRaBTW0qEnAPXM0Uo0OFQfLIYGAkHv1i4cQN6CIu0HAD3Tobeo5e6OHzDdFJzqFjJESJl2SnhAo88PNG92Dii/R/2M8lqDdHTLgxFobaCcZnLhYRtvq8k/JWYczlGzigK10vm4h+C6iPggQ3Scfg+BDn20uRgV+ZjulkqB7Vd/38ubv95LPNJz1IyyHCf/rqQ1Lc9DuO+oSIoXSH3a4T2973A8FkU5ESL7s2YX/0WzQ5/J8xVPflLxdCLokQXGtFgTgq2Gw+VyOWgpAQ29N/AD4+ZDUA1qgzXIobQNyoFt7Gt7FuSqhiBx4V9hfbbfpYMZ0DuKVtw7HImyiOa8cl1AjV8herx0puEn57qmPvZ5P/59TwUlIk1EdpoUp+koZrGinyo8pEHf+g6d0S35iY+kt9uDfu0y234DGj76Sw=="}]}
org.elasticsearch.index.mapper.StrictDynamicMappingException: mapping set to strict, dynamic introduction of [nameIndexId] within [_doc] is not allowed
	at org.elasticsearch.index.mapper.DocumentParser.parseDynamicValue(DocumentParser.java:815) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.index.mapper.DocumentParser.parseValue(DocumentParser.java:619) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.index.mapper.DocumentParser.innerParseObject(DocumentParser.java:427) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.index.mapper.DocumentParser.parseObjectOrNested(DocumentParser.java:395) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.index.mapper.DocumentParser.internalParseDocument(DocumentParser.java:112) ~[elasticsearch-7.4.2.jar:7.4.2]
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:71) ~[elasticsearch-7.4.2.jar:7.4.2]
```

**Comment by ayco-at-naturalis** [comment]
That shouldn't be too hard ... in other words you want to map any exception occuring while indexing to a single, custom IndexingException?

**Comment by ayco-at-naturalis** [comment]
Hmmmm ... client.performRequest is in itself not async. I think client.performRequest under the hood still spawns an asynchronous request, and then waits. But you would expect the es client to handle any http response appropriately. I anyhow do (indeed) not understand how this exception bubbles up. Do we have a full stack trace? Or is this message from the es server log? Otherwise I can put some log statements in executeRequest. Will think about it some more.

**Comment by mdoering** [comment]
The problem is exactly that is does not bubble up. It is silently swallowed and I only found it in the ES logs (see above).
As it is a batch update I bet ES does an async update and the http request itself is probably only transmitting the data and returns before it is actually fully processed. So the request comes in fine, is checked that it is semantically correct and gets pushed to some internal ES "queue" for updating which at some point fails after the http response was already sent. But thats just my unproven theory. If true it would mean we have no chance to catch this...

**Comment by ayco-at-naturalis** [comment]
Yes, I have one been digging in the source code of performRequest (I guess when we got the timeouts :-)) and it didn't seem ultra-solid, so what you describe seems a likely explanation. Certainly about the async update, because its non-asynchronous methods just wrap the asynchronous methods. Perhaps upgrading to ES 7.5.6 would solve it, but I don't know if this issue was explicitly mentioned in the version history.

**Comment by ayco-at-naturalis** [comment]
Yes, I have once been digging in the source code of performRequest (I guess when we got the timeouts :-)) and it didn't seem ultra-solid, so what you describe seems a likely explanation. Certainly about the async update, because its non-asynchronous methods just wrap the asynchronous methods. Perhaps upgrading to ES 7.5.6 would solve it, but I don't know if this issue was explicitly mentioned in the version history.

**Comment by mdoering** [comment]
we just upgraded to postgres 13 before we go live with the code in a few weeks.
Is it worthwhile upgrading ES to the latest before that too?

**Comment by mdoering** [comment]
we just upgraded to postgres 13 before we go live with the code in a few weeks.
Is it worthwhile upgrading ES to the latest before that too?

**Comment by ayco-at-naturalis** [comment]
Hmmm, that makes me think, maybe we should after all do asynchronous, so we have better control over what happens. We could, just like ES it self block until the request comes back to mimick non-asynchronicity.

**Comment by mdoering** [comment]
but that would slow down our indexing if we block?
It takes up already most of the import and sync time and is the bottleneck. Mostly due to very expensive recursive reads in postgres though.

**Comment by ayco-at-naturalis** [comment]
I wouldn't just update to 8 until you or I have ample time to test it. But upgrading to the latest 7.x version should be innocuous (although with ES you never quite know for sure)

**Comment by ayco-at-naturalis** [comment]
> but that would slow down our indexing if we block?
> It takes up already most of the import and sync time and is the bottleneck. Mostly due to very expensive recursive reads in postgres though.

Well - I mean we could mimick doing a non-asynchronous request (but just be more in control), as have done until now.

We could of course also go "full-throttle" asynchronous, but then we have to be even more alert on the HTTP 429 (Too Many Requests) and similar consequences.

If the indexing happens in the blink of an eye compared to all the ploughing of postgres, it might not gain us much. Otherwise yes, letting go of synchronous requests is a good idea.

**Comment by ayco-at-naturalis** [comment]
Unfortunately I don't have much time the coming 2/3 weeks ... can it wait that long?

**Comment by mdoering** [comment]
yes. Let's first get things public before we do this step. 
But first Naturalis needs to hand over the CoL DNS entry to GBIF ;)

**Comment by ayco-at-naturalis** [comment]
Ah .. maybe you should know we've suffered a sudden drain of infrastructure guys (e.g. Hugo no longer works for us). If Olaf didn't tell you, it's probably best to now contact david.heijkamp@naturalis.nl

**Comment by mdoering** [comment]
thanks, I'll give David a try
