### ISSUE TITLE
Import failed from deadlock

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#916]
ITIS failed to import due to a deadlock error.

[Logs](https://logs.gbif.org/app/discover#/context/463d38b0-fe44-11ea-93de-b97c40066ce8/E-O33HUBU86CouzbnrbM?_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!())&_g=(filters:!())):

```
org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 17619 waits for AccessExclusiveLock on relation 10954356 of database 16520; blocked by process 21853.
Process 21853 waits for AccessShareLock on relation 10954398 of database 16520; blocked by process 17619.
  Hint: See server log for query details.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy187.deleteTable(Unknown Source)
	at life.catalogue.db.mapper.DatasetPartitionMapper.lambda$delete$6(DatasetPartitionMapper.java:180)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.db.mapper.DatasetPartitionMapper.delete(DatasetPartitionMapper.java:180)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.apache.ibatis.binding.MapperProxy.invokeDefaultMethod(MapperProxy.java:76)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:51)
	at com.sun.proxy.$Proxy187.delete(Unknown Source)
	at life.catalogue.dao.Partitioner.partition(Partitioner.java:50)
	at life.catalogue.dao.Partitioner.partition(Partitioner.java:35)
	at life.catalogue.importer.PgImport.call(PgImport.java:76)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:240)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:120)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 17619 waits for AccessExclusiveLock on relation 10954356 of database 16520; blocked by process 21853.
Process 21853 waits for AccessShareLock on relation 10954398 of database 16520; blocked by process 17619.
  Hint: See server log for query details.
### The error may exist in life/catalogue/db/mapper/DatasetPartitionMapper.xml
### The error may involve life.catalogue.db.mapper.DatasetPartitionMapper.deleteTable-Inline
### The error occurred while setting parameters
### SQL: DROP TABLE IF EXISTS vernacular_name_2144 CASCADE;     DROP SEQUENCE IF EXISTS vernacular_name_2144_id_seq;
### Cause: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 17619 waits for AccessExclusiveLock on relation 10954356 of database 16520; blocked by process 21853.
Process 21853 waits for AccessShareLock on relation 10954398 of database 16520; blocked by process 17619.
  Hint: See server log for query details.
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy187.deleteTable(Unknown Source)
	at life.catalogue.db.mapper.DatasetPartitionMapper.lambda$delete$6(DatasetPartitionMapper.java:180)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.db.mapper.DatasetPartitionMapper.delete(DatasetPartitionMapper.java:180)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.apache.ibatis.binding.MapperProxy.invokeDefaultMethod(MapperProxy.java:76)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:51)
	at com.sun.proxy.$Proxy187.delete(Unknown Source)
	at life.catalogue.dao.Partitioner.partition(Partitioner.java:50)
	at life.catalogue.dao.Partitioner.partition(Partitioner.java:35)
	at life.catalogue.importer.PgImport.call(PgImport.java:76)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:240)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:120)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 17619 waits for AccessExclusiveLock on relation 10954356 of database 16520; blocked by process 21853.
Process 21853 waits for AccessShareLock on relation 10954398 of database 16520; blocked by process 17619.
  Hint: See server log for query details.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 20 common frames omitted

```

**Comment by gdower** [comment]
I'm going to try to import it again in case it was a temporary issue.

**Comment by mdoering** [comment]
I think that was because I did run a parallel search index rebuilt. Should not happen regularly and ITIS did go through this time
