### ISSUE TITLE
Sync failing for Pterophoroidea because of name_rel_3 constraint

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#951]
Sync is failing for the Pterophoroidea sector because `Key (reference_id)=(911) is not present in table "reference_3" `but the [911 record actually is present](https://data.catalogueoflife.org/catalogue/3/dataset/1199/references?limit=1&offset=1815). I haven't seen the raw data for Donald's dataset, but the the [verbatim info looks correct](https://data.catalogueoflife.org/dataset/1199/verbatim?q=911&type=col%3ANameRelation&type=col%3AReference).

[Logs](https://logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-90d,to:now))&_a=(columns:!(level,sectorKey,service,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:sector,negate:!f,params:(query:'488'),type:phrase),query:(match_phrase:(sector:'488'))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:attempt,negate:!f,params:(query:'10'),type:phrase),query:(match_phrase:(attempt:'10')))),index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',interval:auto,query:(language:kuery,query:''),sort:!())):
```
org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.NameRelationMapper.create (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_rel_3 ( 
    dataset_key,
    sector_key,
    name_id,
    related_name_id,
     
    verbatim_key,
    type,
    reference_id,
    remarks,
    created_by,
    modified_by
   
   , created, modified )
    VALUES ( 
    3,
    NULL,
    'd6c0a0a4-8c35-401c-8611-9bd5a1747c0b',
    'b7769dbd-1ffb-4d5e-b662-18a82783ffa1',
    NULL,
    'TYPE'::NOMRELTYPE,
    '911',
    'original designation',
    10,
    10
   , now(), now() )
RETURNING * was aborted: ERROR: insert or update on table "name_rel_3" violates foreign key constraint "name_rel_3_published_in_id_fkey"
  Detail: Key (reference_id)=(911) is not present in table "reference_3".  Call getNextException to see other errors in the batch.
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:148)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:242)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:223)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:217)
	at life.catalogue.assembly.SectorSync.copyNameRelations(SectorSync.java:286)
	at life.catalogue.assembly.SectorSync.processTree(SectorSync.java:251)
	at life.catalogue.assembly.SectorSync.doWork(SectorSync.java:69)
	at life.catalogue.assembly.SectorRunnable.run(SectorRunnable.java:94)
	at life.catalogue.assembly.SectorSync.run(SectorSync.java:34)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO name_rel_3 ( 
    dataset_key,
    sector_key,
    name_id,
    related_name_id,
     
    verbatim_key,
    type,
    reference_id,
    remarks,
    created_by,
    modified_by
   
   , created, modified )
    VALUES ( 
    3,
    NULL,
    'd6c0a0a4-8c35-401c-8611-9bd5a1747c0b',
    'b7769dbd-1ffb-4d5e-b662-18a82783ffa1',
    NULL,
    'TYPE'::NOMRELTYPE,
    '911',
    'original designation',
    10,
    10
   , now(), now() )
RETURNING * was aborted: ERROR: insert or update on table "name_rel_3" violates foreign key constraint "name_rel_3_published_in_id_fkey"
  Detail: Key (reference_id)=(911) is not present in table "reference_3".  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2286)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:521)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:870)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1639)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:122)
	... 15 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "name_rel_3" violates foreign key constraint "name_rel_3_published_in_id_fkey"
  Detail: Key (reference_id)=(911) is not present in table "reference_3".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	... 22 common frames omitted
```

**Comment by gdower** [comment]
I edited above to remove the part on record 911 actually being present, because somehow the interface switched me to the other dataset from Donald which does have a 911 reference record. It might have been my mistake because I was also investigating a failed sync in that dataset.

It is missing the 911 record, but probably that should not cause the sync to fail.

**Comment by mdoering** [comment]
Thats the first time we actually sync name relations I suspect, looks like a genuine bug
