### ISSUE TITLE
Importer failing if the parent binomial is missing for infraspecies

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#954]
ITIS is [missing some parent binomials for infraspecies](https://github.com/CatalogueOfLife/data/issues/231), which caused the importer to fail possibly from the [new PARENT_SPECIES_MISSING issue](https://github.com/CatalogueOfLife/backend/commit/c007a3081c7e9655405a4afb1f5df6fb9e271a90). We're working with ITIS to fix the data issue.

[Logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/CuFxJncBU86Couzb9Xgt?_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!t,index:'37c669c0-2a5c-11eb-9ca0-ddc1af98892f',key:dataset,negate:!f,params:(query:'2144'),type:phrase),query:(match_phrase:(dataset:'2144')))))&_g=(filters:!())):
```
org.apache.ibatis.executor.BatchExecutorException: life.catalogue.db.mapper.VerbatimRecordMapper.create (batch index #1) failed. Cause: java.sql.BatchUpdateException: Batch entry 7,864 INSERT INTO verbatim_2144 ( 
    dataset_key,
     
    line,
    file,
    type,
    terms,
    issues
   
   )
    VALUES ( 
    2144,
    733417,
    'Name.tsv',
    'col:Name',
    '{"col:authorship":"Cleve-Euler","col:rank":"variety","col:specificEpithet":"perpusilla","col:infraspecificEpithet":"distans","col:scientificName":"Navicula perpusilla var. distans","col:ID":"1021265","col:status":"http://purl.obolibrary.org/obo/NOMEN_0000383","col:genus":"Navicula","http://unknown.org/original":"0","col:code":"botanical","col:link":"https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1021265"}'::jsonb,
    '{"NOMENCLATURAL_STATUS_INVALID","PARENT_SPECIES_MISSING"}'::ISSUE[]
   )
RETURNING * was aborted: ERROR: invalid input value for enum issue: "PARENT_SPECIES_MISSING"  Call getNextException to see other errors in the batch.
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:148)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:129)
	at org.apache.ibatis.executor.BaseExecutor.flushStatements(BaseExecutor.java:122)
	at org.apache.ibatis.executor.BaseExecutor.commit(BaseExecutor.java:242)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:223)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.commit(DefaultSqlSession.java:217)
	at life.catalogue.importer.PgImport.commitVerbatimBatch(PgImport.java:232)
	at life.catalogue.importer.PgImport.insertVerbatim(PgImport.java:221)
	at life.catalogue.importer.PgImport.call(PgImport.java:104)
	at life.catalogue.importer.ImportJob.importDataset(ImportJob.java:240)
	at life.catalogue.importer.ImportJob.run(ImportJob.java:120)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.sql.BatchUpdateException: Batch entry 7,864 INSERT INTO verbatim_2144 ( 
    dataset_key,
     
    line,
    file,
    type,
    terms,
    issues
   
   )
    VALUES ( 
    2144,
    733417,
    'Name.tsv',
    'col:Name',
    '{"col:authorship":"Cleve-Euler","col:rank":"variety","col:specificEpithet":"perpusilla","col:infraspecificEpithet":"distans","col:scientificName":"Navicula perpusilla var. distans","col:ID":"1021265","col:status":"http://purl.obolibrary.org/obo/NOMEN_0000383","col:genus":"Navicula","http://unknown.org/original":"0","col:code":"botanical","col:link":"https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=1021265"}'::jsonb,
    '{"NOMENCLATURAL_STATUS_INVALID","PARENT_SPECIES_MISSING"}'::ISSUE[]
   )
RETURNING * was aborted: ERROR: invalid input value for enum issue: "PARENT_SPECIES_MISSING"  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2286)
	at org.postgresql.core.v3.QueryExecutorImpl.flushIfDeadlockRisk(QueryExecutorImpl.java:1404)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1429)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:507)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:870)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1639)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:128)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.BatchExecutor.doFlushStatements(BatchExecutor.java:122)
	... 15 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: invalid input value for enum issue: "PARENT_SPECIES_MISSING"
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	... 24 common frames omitted
```

**Comment by mdoering** [comment]
ouch, I forgot to update the db enum with the last deploy. Fixed

**Comment by mdoering** [comment]
The error at least shows that the issue is being flagged correctly :)
Please reimport
