### ISSUE TITLE
Deadlock issue on DatasetPartitionMapper name_usage_2212

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#987]
I hit a database deadlock issue on prod ChecklistBank. Not sure if it matters, but at the time of import there was a running release. I am running the same import on dev and it's taking a very long time for a pretty small dataset which is why I tried prod. I'll try again and re-open this if it's still an issue.

```
PersistenceException: ### Error updating database. Cause: org.postgresql.util.PSQLException: ERROR: deadlock detected Detail: Process 1648 waits for AccessExclusiveLock on relation 11021708 of database 11005483; blocked by process 6738. Process 6738 waits for AccessShareLock on relation 11024547 of database 11005483; blocked by process 1648. Hint: See server log for query details. ### The error may exist in life/catalogue/db/mapper/DatasetPartitionMapper.xml ### The error may involve life.catalogue.db.mapper.DatasetPartitionMapper.deleteTable-Inline ### The error occurred while setting parameters ### SQL: DROP TABLE IF EXISTS name_usage_2212 CASCADE; DROP SEQUENCE IF EXISTS name_usage_2212_id_seq; ### Cause: org.postgresql.util.PSQLException: ERROR: deadlock detected Detail: Process 1648 waits for AccessExclusiveLock on relation 11021708 of database 11005483; blocked by process 6738. Process 6738 waits for AccessShareLock on relation 11024547 of database 11005483; blocked by process 1648. Hint: See server log for query details.
```

**Comment by mdoering** [comment]
The dataset is indeed small and the import hangs when starting the ES indexing.
I tried to upload the same archive again to DEV and the same thing happens. Both importer threads hang here:

```
    at app//life.catalogue.es.query.TermQuery.getAnalyzer(TermQuery.java:33)
    at app//life.catalogue.es.query.TermQuery.<init>(TermQuery.java:12)
    at app//life.catalogue.es.EsUtil.deleteDataset(EsUtil.java:164)
    at app//life.catalogue.es.nu.NameUsageIndexServiceEs.createOrEmptyIndex(NameUsageIndexServiceEs.java:277)
    at app//life.catalogue.es.nu.NameUsageIndexServiceEs.buildDatasetIndexingHandler(NameUsageIndexServiceEs.java:68)
    at app//life.catalogue.importer.PgImport.insertUsages(PgImport.java:378)
    at app//life.catalogue.importer.PgImport.call(PgImport.java:114)
    at app//life.catalogue.importer.ImportJob.importDataset(ImportJob.java:240)
    at app//life.catalogue.importer.ImportJob.run(ImportJob.java:120)
```

**Comment by mdoering** [comment]
It works locally. I restarted dev, it seems like an ES connection problem again. 
I have added a new health test that does a real ES query - hopefully that can monitor when sth with ES is bad.

**Comment by mdoering** [comment]
Ive reimported your archive into your dataset on dev now fine and quick.

**Comment by gdower** [comment]
For some reason, it did import successfully on prod the 2nd try in less than 30 seconds, so whatever the issue was seemed intermittent.
