### ISSUE TITLE
Foreign key constraint on `name_usage_2295_name_id_fkey`

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/backend#996]
The preview release failed with a foreign key constraint on `name_usage_2295_name_id_fkey`. The referenced nameID `4b4998a5-efb9-4712-99cb-a11e284320ab` is [Lophogastrida G. O. Sars, 1870](http://api.catalogueoflife.org/dataset/3/name/4b4998a5-efb9-4712-99cb-a11e284320ab) from ITIS. It's [not flagged](https://data.catalogueoflife.org/dataset/2144/verbatim?q=Lophogastrida&type=col%3AName) with any importer issues.

[Logs](https://logs.gbif.org/app/discover#/context/37c669c0-2a5c-11eb-9ca0-ddc1af98892f/_LJOlHgBU86CouzbFx70?_a=(columns:!(level,datasetKey,service,logger_name,message),filters:!())&_g=(filters:!())):
```
org.apache.ibatis.exceptions.PersistenceException: 
### Error updating database.  Cause: org.postgresql.util.PSQLException: ERROR: insert or update on table "name_usage_2295" violates foreign key constraint "name_usage_2295_name_id_fkey"
  Detail: Key (name_id)=(4b4998a5-efb9-4712-99cb-a11e284320ab) is not present in table "name_2295".
### The error may exist in life/catalogue/db/mapper/DatasetPartitionMapper.xml
### The error may involve life.catalogue.db.mapper.DatasetPartitionMapper.createFk-Inline
### The error occurred while setting parameters
### SQL: ALTER TABLE name_usage_2295 ADD FOREIGN KEY (name_id) REFERENCES name_2295      ON DELETE CASCADE
### Cause: org.postgresql.util.PSQLException: ERROR: insert or update on table "name_usage_2295" violates foreign key constraint "name_usage_2295_name_id_fkey"
  Detail: Key (name_id)=(4b4998a5-efb9-4712-99cb-a11e284320ab) is not present in table "name_2295".
	at org.apache.ibatis.exceptions.ExceptionFactory.wrapException(ExceptionFactory.java:30)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:199)
	at org.apache.ibatis.binding.MapperMethod.execute(MapperMethod.java:67)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:57)
	at com.sun.proxy.$Proxy151.createFk(Unknown Source)
	at life.catalogue.db.mapper.DatasetPartitionMapper.lambda$attach$14(DatasetPartitionMapper.java:224)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at life.catalogue.db.mapper.DatasetPartitionMapper.lambda$attach$15(DatasetPartitionMapper.java:224)
	at java.base/java.util.Map.forEach(Map.java:661)
	at life.catalogue.db.mapper.DatasetPartitionMapper.attach(DatasetPartitionMapper.java:224)
	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:710)
	at org.apache.ibatis.binding.MapperProxy.invokeDefaultMethod(MapperProxy.java:76)
	at org.apache.ibatis.binding.MapperProxy.invoke(MapperProxy.java:51)
	at com.sun.proxy.$Proxy151.attach(Unknown Source)
	at life.catalogue.dao.Partitioner.attach(Partitioner.java:105)
	at life.catalogue.dao.Partitioner.attach(Partitioner.java:91)
	at life.catalogue.release.AbstractProjectCopy.run(AbstractProjectCopy.java:132)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.postgresql.util.PSQLException: ERROR: insert or update on table "name_usage_2295" violates foreign key constraint "name_usage_2295_name_id_fkey"
  Detail: Key (name_id)=(4b4998a5-efb9-4712-99cb-a11e284320ab) is not present in table "name_2295".
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.execute(PgPreparedStatement.java:153)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.apache.ibatis.executor.statement.PreparedStatementHandler.update(PreparedStatementHandler.java:47)
	at org.apache.ibatis.executor.statement.RoutingStatementHandler.update(RoutingStatementHandler.java:74)
	at org.apache.ibatis.executor.SimpleExecutor.doUpdate(SimpleExecutor.java:50)
	at org.apache.ibatis.executor.BaseExecutor.update(BaseExecutor.java:117)
	at org.apache.ibatis.session.defaults.DefaultSqlSession.update(DefaultSqlSession.java:197)
	... 19 common frames omitted
```

**Comment by yroskov** [comment]
I established order Lophogastrida as a new ITIS sector recently (2021-04-02): https://github.com/CatalogueOfLife/testing/issues/8

**Comment by gdower** [comment]
I think we figured it out and are going to run another release. I'll re-open this if we still have an issue.
